/**
 * The shared clinical fixture corpus.
 *
 * One list of named assessments, read by the browser walkthrough audit
 * (scripts/audit/questionnaire-traces.ts), the frontend tests and the
 * frontend-to-backend parity suite
 * (supabase/functions/tests/clinical-parity.test.ts), so the scenarios the
 * browser verifies are exactly the scenarios the trusted server must match.
 */
import type { ContextSpec, Script } from './clinical-walk.ts';

export interface NamedTrace {
  id: string;
  title: string;
  spec: ContextSpec;
  /** Browser inputs: date of birth, sex label, region label, concern label. */
  ui: { dob: string; sex: 'Female' | 'Male'; region: string; faceRegion?: string; concern: string };
  script: Script;
}

export const TRACES: readonly NamedTrace[] = [
  {
    id: '01-age4-ear',
    title: 'Age 4, ear',
    spec: { region: 'face', face: 'patient-left-ear', concern: 'pain', age: 4 },
    ui: { dob: '15/01/2022', sex: 'Female', region: 'Face', faceRegion: 'patient-left-ear', concern: 'Pain or discomfort' },
    script: {
      'intake-pediatric-ear-observation': 'discharge',
      'intake-face-ear-persistence': 'two-weeks-plus',
      'intake-face-ear-associated': 'discharge+hearing',
    },
  },
  {
    id: '02-age4-abdomen',
    title: 'Age 4, tummy',
    spec: { region: 'upper-abdomen', concern: 'pain', age: 4, sex: 'male' },
    ui: { dob: '15/01/2022', sex: 'Male', region: 'Upper abdomen', concern: 'Pain or discomfort' },
    script: { 'intake-abdominal-associated': 'constipation', 'intake-history-duration': 'longer' },
  },
  {
    id: '03-age10-knee',
    title: 'Age 10, knee injury',
    spec: { region: 'right-knee', concern: 'injury', age: 10, sex: 'male' },
    ui: { dob: '15/01/2016', sex: 'Male', region: 'Right knee', concern: 'Injury' },
    script: {
      'intake-injury-associated-detail': 'fall',
      'intake-injury-function': 'limping',
      'intake-msk-duration': 'two-to-six-weeks',
      'intake-msk-mechanical': 'gives-way',
    },
  },
  {
    id: '04-age10-throat',
    title: 'Age 10, recurrent sore throats',
    spec: { region: 'neck', concern: 'throat', age: 10 },
    ui: { dob: '15/01/2016', sex: 'Female', region: 'Neck', concern: 'Sore throat' },
    script: {
      'intake-throat-detail': 'sore',
      'intake-throat-duration': 'under-one-week',
      'intake-throat-recurrence': 'seven-in-year',
      'intake-throat-impact': 'yes',
    },
  },
  {
    id: '05-age15-self-throat',
    title: 'Age 15 answering for themselves, short sore throat',
    spec: { region: 'neck', concern: 'throat', age: 15, reporter: 'young-person' },
    ui: { dob: '15/01/2011', sex: 'Female', region: 'Neck', concern: 'Sore throat' },
    script: { 'intake-throat-detail': 'sore', 'intake-throat-duration': 'under-one-week', 'intake-throat-recurrence': 'first' },
  },
  {
    id: '06-age15-caregiver-throat',
    title: 'Age 15 with a caregiver answering, persistent hoarseness',
    spec: { region: 'neck', concern: 'throat', age: 15, reporter: 'caregiver' },
    ui: { dob: '15/01/2011', sex: 'Male', region: 'Neck', concern: 'Sore throat' },
    script: {
      'intake-throat-detail': 'hoarse',
      'intake-throat-duration': 'over-three-weeks',
      'intake-throat-associated': 'none',
      'intake-throat-recurrence': 'first',
    },
  },
  {
    id: '07-age7-breathing',
    title: 'Age 7, breathing, wheeze that keeps happening',
    spec: { region: 'chest', concern: 'breathing', age: 7, sex: 'male' },
    ui: { dob: '15/01/2019', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: { 'intake-breathing-detail': 'wheeze', 'intake-breathing-recurrence': 'keeps-happening' },
  },
  {
    id: '08-adult-reproductive',
    title: 'Adult, lower abdomen, reproductive',
    spec: { region: 'lower-abdomen', concern: 'reproductive-pelvic-change' as never, age: 36, sex: 'female' },
    ui: { dob: '15/01/1990', sex: 'Female', region: 'Lower abdomen', concern: 'Pelvic or reproductive change' },
    script: { 'intake-lower-reproductive-detail': 'bleeding', 'intake-lower-reproductive-timing': 'between-periods' },
  },
  {
    id: '09-adult-constipation',
    title: 'Adult, persistent constipation',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 62, sex: 'male' },
    ui: { dob: '15/01/1964', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: {
      'intake-lower-bowel-detail': 'constipation',
      'intake-lower-bowel-persistence': 'regularly-recurrent',
      'intake-lower-bowel-alarm-feature': 'weight-loss',
    },
  },
  {
    id: '10-adult-ear',
    title: 'Adult, ear',
    spec: { region: 'face', face: 'patient-right-ear', concern: 'pain', age: 36, sex: 'male' },
    ui: { dob: '15/01/1990', sex: 'Male', region: 'Face', faceRegion: 'patient-right-ear', concern: 'Pain or discomfort' },
    script: { 'intake-face-ear-detail': 'inside', 'intake-face-ear-persistence': 'two-weeks-plus', 'intake-face-ear-associated': 'discharge+hearing' },
  },
  {
    id: '11-adult-nose-persistent-one-sided',
    title: 'Adult, nose, persistent and one-sided',
    spec: { region: 'face', face: 'nose', concern: 'nose-change', age: 36, sex: 'male' },
    ui: { dob: '15/01/1990', sex: 'Male', region: 'Face', faceRegion: 'nose', concern: 'Blocked, runny or smell change' },
    script: {
      'intake-face-nose-detail': 'unsure',
      'intake-face-nose-persistence': 'over-three-months',
      'intake-face-nose-associated': 'one-sided',
    },
  },
  {
    id: '12-adult-eye',
    title: 'Adult, eye',
    spec: { region: 'face', face: 'patient-right-eye', concern: 'eye-redness-discharge', age: 36 },
    ui: { dob: '15/01/1990', sex: 'Female', region: 'Face', faceRegion: 'patient-right-eye', concern: 'Redness or discharge' },
    script: { 'intake-face-eye-detail': 'gritty', 'intake-face-eye-associated': 'red' },
  },
  {
    id: '13-adult-stomach',
    title: 'Adult, stomach',
    spec: { region: 'upper-abdomen', concern: 'pain', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Upper abdomen', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'unsure',
      'intake-history-current-impact': '2',
      // How often, in the NHS heartburn and indigestion bands (replaces the generic duration and pattern).
      'intake-upper-gi-frequency': 'first',
      'upper-abdominal-pain-exertional': 'no',
      'intake-history-onset': 'sudden',
      'upper-abdominal-pain-meal-relation': 'yes',
      'upper-abdominal-pain-burning': 'yes',
      'upper-abdominal-pain-nausea-vomiting': 'yes',
    },
  },
  {
    id: '14-urgent-continues',
    title: 'Urgent but continuable: age 10 recurrent sore throats with a very painful throat',
    spec: { region: 'neck', concern: 'throat', age: 10 },
    ui: { dob: '15/01/2016', sex: 'Female', region: 'Neck', concern: 'Sore throat' },
    script: {
      'intake-throat-detail': 'painful-swallow',
      'intake-throat-duration': 'under-one-week',
      'intake-throat-recurrence': 'seven-in-year',
      'intake-throat-impact': 'yes',
      'safety-throat-urgent': 'yes',
    },
  },
  {
    id: '15-hard-stop',
    title: 'True hard stop: age 3, breathing, chest pulling in',
    spec: { region: 'chest', concern: 'breathing', age: 3, sex: 'male' },
    ui: { dob: '15/01/2023', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: { 'intake-breathing-detail': 'fast', 'safety-pediatric-chest-indrawing-or-stridor': 'yes' },
  },
  {
    id: '16-adult-constipation-recent',
    title: 'Adult, constipation, recent first episode',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 34, sex: 'female' },
    ui: { dob: '15/01/1992', sex: 'Female', region: 'Lower abdomen', concern: 'Bowel change' },
    script: {
      'intake-lower-bowel-detail': 'constipation',
      'intake-lower-bowel-persistence': 'recent-first',
      'intake-lower-bowel-alarm-feature': 'neither',
    },
  },
  {
    id: '17-adult-nose-short',
    title: 'Adult, nose, short and simple',
    spec: { region: 'face', face: 'nose', concern: 'nose-change', age: 36, sex: 'female' },
    ui: { dob: '15/01/1990', sex: 'Female', region: 'Face', faceRegion: 'nose', concern: 'Blocked, runny or smell change' },
    script: {
      'intake-face-nose-detail': 'blocked',
      'intake-face-nose-persistence': 'one-to-three-weeks',
      'intake-face-nose-treatment': 'not-tried',
    },
  },
  {
    id: '18-adult-face-numbness',
    title: 'Adult, face numbness with a rash',
    spec: { region: 'face', face: 'patient-left-cheek', concern: 'numbness-tingling', age: 45, sex: 'female' },
    ui: { dob: '15/01/1981', sex: 'Female', region: 'Face', faceRegion: 'patient-left-cheek', concern: 'Numbness or tingling' },
    script: {
      'intake-history-symptom-character': 'pins-needles',
      'intake-neurologic-associated-detail': 'one-sided',
      // How it has changed (NICE NG127) replaces the generic pattern question.
      'intake-neurologic-course': 'same',
      'intake-neurologic-waking': 'no',
      'intake-neurologic-associated-features': 'pain+rash',
    },
  },
  {
    id: '19-adult-bowel-bleeding',
    title: 'Adult, blood in the poo, not heavy',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 58, sex: 'male' },
    ui: { dob: '15/01/1968', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: {
      'intake-lower-bowel-detail': 'blood',
      'intake-lower-bowel-bleeding-duration': 'three-weeks-plus',
      'intake-lower-bowel-persistence': 'not-improving',
    },
  },
  {
    id: 'H1-headache-nonspecific',
    title: 'H1. Adult headache without a supported narrower-service pattern',
    spec: { region: 'head', concern: 'pain', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Head', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'pressure',
      'intake-history-current-impact': '1',
      'intake-history-duration': 'today',
      'headache-activity-worsening': 'no',
      'headache-light-sound-sensitivity': 'no',
      'headache-nausea-vomiting': 'no',
      'headache-same-side-eye-nose': 'no',
      'headache-one-sided': 'no',
      'headache-pulsating': 'no',
      'intake-headache-sinus-symptoms': 'no',
      'intake-headache-features': 'none',
    },
  },
  {
    id: 'H2-headache-neurology',
    title: 'H2. Adult headache with two source-backed secondary-headache features',
    spec: { region: 'head', concern: 'pain', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Head', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'pressure',
      'intake-history-current-impact': '2',
      'intake-history-duration': 'longer',
      'headache-activity-worsening': 'no',
      'headache-light-sound-sensitivity': 'no',
      'headache-nausea-vomiting': 'no',
      'headache-same-side-eye-nose': 'no',
      'headache-one-sided': 'no',
      'headache-pulsating': 'no',
      'intake-headache-sinus-symptoms': 'no',
      'intake-headache-features': 'cough-strain+posture',
    },
  },
  {
    id: 'H3-headache-ent',
    title: 'H3. Adult headache with a one-sided nasal and facial-pressure pattern',
    spec: { region: 'head', concern: 'pain', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Head', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'pressure',
      'intake-history-current-impact': '2',
      'intake-history-duration': 'longer',
      'headache-activity-worsening': 'no',
      'headache-light-sound-sensitivity': 'no',
      'headache-nausea-vomiting': 'no',
      'headache-same-side-eye-nose': 'no',
      'headache-one-sided': 'no',
      'headache-pulsating': 'no',
      'intake-headache-sinus-symptoms': 'yes',
      'intake-headache-features': 'none',
      'intake-headache-sinus-pattern': 'one-sided',
    },
  },
  {
    id: 'H4-headache-hard-stop',
    title: 'H4. Adult headache with sudden extreme pain: immediate interruption',
    spec: { region: 'head', concern: 'pain', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Head', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'sharp',
      'intake-history-current-impact': '4',
      'intake-history-duration': 'today',
      'safety-headache-sudden-extremely-painful': 'yes',
    },
  },
  {
    id: 'H5-headache-unresolved',
    title: 'H5. Adult headache with uncertain features and insufficient supported evidence',
    spec: { region: 'head', concern: 'pain', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Head', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'unsure',
      'intake-history-current-impact': '1',
      'intake-history-duration': 'longer',
      'headache-activity-worsening': 'no',
      'headache-light-sound-sensitivity': 'no',
      'headache-nausea-vomiting': 'no',
      'headache-same-side-eye-nose': 'no',
      'headache-one-sided': 'no',
      'headache-pulsating': 'no',
      'intake-headache-sinus-symptoms': 'unsure',
      'intake-headache-features': 'none',
    },
  },
  {
    id: 'B1-breathing-respiratory',
    title: 'B1. Adult breathlessness with persistent cough and repeated chest illness episodes',
    spec: { region: 'chest', concern: 'breathing', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: {
      'intake-history-symptom-character': 'tight',
      'intake-history-current-impact': '2',
      'intake-history-duration': 'longer',
      'shortness-of-breath-ankle-swelling': 'no',
      'shortness-of-breath-cough': 'yes',
      'shortness-of-breath-night-variation': 'no',
      'shortness-of-breath-palpitations': 'no',
      'shortness-of-breath-lying-flat': 'no',
      'shortness-of-breath-wheeze': 'no',
      'intake-breathing-infections': 'yes',
      'intake-breathing-phlegm': 'no',
      'intake-breathing-activity': 'no',
    },
  },
  {
    id: 'B2-breathing-cardiology',
    title: 'B2. Adult breathlessness with effort, swollen ankles and worse breathing when lying down',
    spec: { region: 'chest', concern: 'breathing', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: {
      'intake-history-symptom-character': 'effort',
      'intake-history-current-impact': '2',
      'intake-history-duration': 'longer',
      'shortness-of-breath-ankle-swelling': 'yes',
      'shortness-of-breath-cough': 'no',
      'shortness-of-breath-night-variation': 'no',
      'shortness-of-breath-palpitations': 'no',
      'shortness-of-breath-lying-flat': 'yes',
      'shortness-of-breath-wheeze': 'no',
    },
  },
  {
    id: 'B3-breathing-ambiguous',
    title: 'B3. Adult breathlessness with no supported narrower-service pattern',
    spec: { region: 'chest', concern: 'breathing', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: {
      'intake-history-symptom-character': 'unsure',
      'intake-history-current-impact': '2',
      'intake-history-duration': 'longer',
      'shortness-of-breath-ankle-swelling': 'no',
      'shortness-of-breath-cough': 'no',
      'shortness-of-breath-night-variation': 'no',
      'shortness-of-breath-palpitations': 'no',
      'shortness-of-breath-lying-flat': 'no',
      'shortness-of-breath-wheeze': 'no',
      'intake-breathing-infections': 'no',
      'intake-breathing-phlegm': 'no',
      'intake-breathing-ankles': 'no',
      'intake-breathing-lying-flat': 'no',
      'intake-breathing-activity': 'no',
    },
  },
  {
    id: 'B4-breathing-urgent-continues',
    title: 'B4. Adult respiratory pattern with coughing blood: urgent but continuable',
    spec: { region: 'chest', concern: 'breathing', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: {
      'intake-history-symptom-character': 'tight',
      'intake-history-current-impact': '2',
      'intake-history-duration': 'longer',
      'safety-shortness-of-breath-coughing-blood': 'yes',
      'shortness-of-breath-ankle-swelling': 'no',
      'shortness-of-breath-cough': 'yes',
      'shortness-of-breath-night-variation': 'no',
      'shortness-of-breath-palpitations': 'no',
      'shortness-of-breath-lying-flat': 'no',
      'shortness-of-breath-wheeze': 'no',
      'intake-breathing-infections': 'yes',
      'intake-breathing-phlegm': 'no',
      'intake-breathing-activity': 'no',
    },
  },
  {
    id: 'B5-breathing-hard-stop',
    title: 'B5. Adult severe breathlessness: immediate interruption',
    spec: { region: 'chest', concern: 'breathing', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: {
      'intake-history-symptom-character': 'air-hunger',
      'intake-history-current-impact': '4',
      'intake-history-duration': 'today',
      'safety-shortness-of-breath-severe': 'yes',
    },
  },
  {
    id: 'UA1-upper-abdomen-injury',
    title: 'UA1. Adult upper-abdomen injury with the specific injury and safety branch',
    spec: { region: 'upper-abdomen', concern: 'injury', age: 35, sex: 'male' },
    ui: { dob: '15/01/1991', sex: 'Male', region: 'Upper abdomen', concern: 'Injury' },
    script: {
      'intake-injury-associated-detail': 'impact',
      'intake-abdomen-injury-timing': 'few-days',
      'intake-abdomen-injury-movement': 'both',
      'intake-abdomen-injury-features': 'bruising+swelling',
      'safety-upper-abdomen-injury-emergency': 'no',
    },
  },
  {
    id: 'UA2-upper-abdomen-other-injury',
    title: 'UA2. Adult upper-abdomen “something else” clarified to the injury branch',
    spec: { region: 'upper-abdomen', concern: 'other', age: 35, sex: 'male' },
    ui: { dob: '15/01/1991', sex: 'Male', region: 'Upper abdomen', concern: 'Something else' },
    script: {
      'intake-other-clarifier': 'injury',
      'intake-injury-associated-detail': 'fall',
      'intake-abdomen-injury-timing': 'today',
      'intake-abdomen-injury-movement': 'moving',
      'intake-abdomen-injury-features': 'none',
      'safety-upper-abdomen-injury-emergency': 'no',
    },
  },
  {
    id: 'UA3-upper-abdomen-bowel',
    title: 'UA3. Adult upper-abdomen bowel change with persistent constipation and an alarm feature',
    spec: { region: 'upper-abdomen', concern: 'bowel-change', age: 35, sex: 'female' },
    ui: { dob: '15/01/1991', sex: 'Female', region: 'Upper abdomen', concern: 'Digestive or bowel change' },
    script: {
      'intake-lower-bowel-detail': 'constipation',
      'intake-lower-bowel-persistence': 'regularly-recurrent',
      'intake-lower-bowel-treatment': 'not-helped',
      'intake-lower-bowel-alarm-feature': 'weight-loss',
      'intake-lower-bowel-systemic': 'none',
    },
  },
];

/** What each base trace must resolve to, identically in the browser and on the trusted server. */
export const BASE_EXPECTED: Readonly<Record<string, { status: 'route' | 'hard-stop'; specialtyId?: string; routeType?: string; fallbackReason?: string; urgency?: 'urgent'; hardStopRuleId?: string }>> = {
  '01-age4-ear': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate' },
  '02-age4-abdomen': { status: 'route', specialtyId: 'paediatrics', routeType: 'parent-fallback' },
  '03-age10-knee': { status: 'route', specialtyId: 'orthopaedics', routeType: 'direction-gate' },
  '04-age10-throat': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate' },
  '05-age15-self-throat': { status: 'route', specialtyId: 'paediatrics', routeType: 'parent-fallback' },
  '06-age15-caregiver-throat': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate' },
  '07-age7-breathing': { status: 'route', specialtyId: 'paediatrics', routeType: 'direction-gate' },
  '08-adult-reproductive': { status: 'route', specialtyId: 'obstetrics-gynaecology', routeType: 'direction-gate' },
  '09-adult-constipation': { status: 'route', specialtyId: 'medical-gastroenterology', routeType: 'direction-gate' },
  '10-adult-ear': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate' },
  '11-adult-nose-persistent-one-sided': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate' },
  '12-adult-eye': { status: 'route', specialtyId: 'ophthalmology', routeType: 'direction-gate' },
  '13-adult-stomach': { status: 'route', specialtyId: 'medical-gastroenterology', routeType: 'weighted-demonstration' },
  '14-urgent-continues': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate', urgency: 'urgent' },
  '15-hard-stop': { status: 'hard-stop' },
  '16-adult-constipation-recent': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback' },
  '17-adult-nose-short': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback' },
  '18-adult-face-numbness': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback' },
  '19-adult-bowel-bleeding': { status: 'route', specialtyId: 'medical-gastroenterology', routeType: 'direction-gate' },
  'H1-headache-nonspecific': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'INSUFFICIENT_SUPPORTED_EVIDENCE' },
  'H2-headache-neurology': { status: 'route', specialtyId: 'neurology', routeType: 'direction-gate' },
  'H3-headache-ent': { status: 'route', specialtyId: 'otorhinolaryngology', routeType: 'direction-gate' },
  'H4-headache-hard-stop': { status: 'hard-stop', hardStopRuleId: 'headache-sudden-extremely-painful' },
  'H5-headache-unresolved': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'INSUFFICIENT_SUPPORTED_EVIDENCE' },
  'B1-breathing-respiratory': { status: 'route', specialtyId: 'respiratory-medicine', routeType: 'direction-gate' },
  'B2-breathing-cardiology': { status: 'route', specialtyId: 'cardiology', routeType: 'direction-gate' },
  'B3-breathing-ambiguous': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'INSUFFICIENT_SUPPORTED_EVIDENCE' },
  'B4-breathing-urgent-continues': { status: 'route', specialtyId: 'respiratory-medicine', routeType: 'direction-gate', urgency: 'urgent' },
  'B5-breathing-hard-stop': { status: 'hard-stop', hardStopRuleId: 'breathing-severe-inability-to-speak' },
  'UA1-upper-abdomen-injury': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'NO_VALIDATED_NARROW_ROUTE' },
  'UA2-upper-abdomen-other-injury': { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'NO_VALIDATED_NARROW_ROUTE' },
  'UA3-upper-abdomen-bowel': { status: 'route', specialtyId: 'medical-gastroenterology', routeType: 'direction-gate' },
};

export interface EdgeFixture {
  id: string;
  spec: ContextSpec;
  script: Script;
  expect: {
    status: 'route' | 'hard-stop';
    specialtyId?: string;
    routeType?: string;
    fallbackReason?: string;
    urgency?: 'urgent';
    hardStopRuleId?: string;
    calibration?: 'SPECIALTY_EVIDENCE_CALIBRATION_REQUIRED';
  };
}

/** Edge cases: physiology, exclusions, safety tiers, paediatric shared services, ambiguity and calibration. */
export const EDGE_FIXTURES: readonly EdgeFixture[] = [
  {
    id: 'female-lower-abdomen-non-reproductive',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 34, sex: 'female' },
    script: { 'intake-lower-associated-system': 'urinary', 'intake-lower-urinary-detail': 'blood', 'intake-lower-urinary-pattern': 'recurrent' },
    expect: { status: 'route', specialtyId: 'urology', routeType: 'direction-gate' },
  },
  {
    id: 'male-lower-abdomen',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 40, sex: 'male' },
    script: {},
    expect: { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'INSUFFICIENT_SUPPORTED_EVIDENCE' },
  },
  {
    id: 'ear-competing-dental-pattern',
    spec: { region: 'face', face: 'patient-right-ear', concern: 'pain', age: 40, sex: 'male' },
    script: { 'intake-face-ear-detail': 'inside', 'intake-face-ear-persistence': 'recurrent', 'intake-face-ear-associated': 'discharge+jaw-tooth' },
    expect: { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'EXCLUDED_BY_COMPETING_PATTERN' },
  },
  {
    id: 'short-uncomplicated-throat',
    spec: { region: 'neck', concern: 'throat', age: 10 },
    script: { 'intake-throat-detail': 'sore', 'intake-throat-duration': 'under-one-week', 'intake-throat-recurrence': 'first' },
    expect: { status: 'route', specialtyId: 'paediatrics', routeType: 'parent-fallback' },
  },
  {
    id: 'rectal-bleeding-urgent',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 55, sex: 'male' },
    script: { 'intake-lower-bowel-detail': 'blood', 'safety-rectal-bleeding-urgent': 'yes' },
    expect: { status: 'route', specialtyId: 'medical-gastroenterology', routeType: 'direction-gate', urgency: 'urgent' },
  },
  {
    id: 'rectal-bleeding-hard-stop',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 55, sex: 'male' },
    script: { 'intake-lower-bowel-detail': 'blood', 'safety-rectal-bleeding-heavy': 'yes' },
    expect: { status: 'hard-stop', hardStopRuleId: 'rectal-bleeding-heavy' },
  },
  {
    id: 'adult-skin-criteria',
    spec: { region: 'left-forearm', concern: 'skin-change', age: 34 },
    script: { 'intake-skin-associated-detail': 'mole', 'intake-skin-duration': 'keeps-returning', 'intake-skin-features': 'changed' },
    expect: { status: 'route', specialtyId: 'dermatology', routeType: 'direction-gate' },
  },
  {
    id: 'pediatric-eye-squint',
    spec: { region: 'face', face: 'patient-left-eye', concern: 'pain', age: 6 },
    script: { 'intake-face-eye-detail': 'squint', 'intake-face-eye-squint-pattern': 'all-the-time' },
    expect: { status: 'route', specialtyId: 'ophthalmology', routeType: 'direction-gate' },
  },
  {
    id: 'pediatric-skin',
    spec: { region: 'left-forearm', concern: 'skin-change', age: 10 },
    script: { 'intake-skin-associated-detail': 'itchy-raised', 'intake-skin-duration': 'one-to-four-weeks', 'intake-skin-treatment': 'not-settled', 'intake-skin-features': 'changed' },
    expect: { status: 'route', specialtyId: 'dermatology', routeType: 'direction-gate' },
  },
  {
    id: 'pediatric-injury',
    spec: { region: 'right-ankle', concern: 'injury', age: 9, sex: 'male' },
    script: { 'intake-injury-associated-detail': 'fall', 'intake-injury-function': 'limping', 'intake-msk-duration': 'two-to-six-weeks' },
    expect: { status: 'route', specialtyId: 'orthopaedics', routeType: 'direction-gate' },
  },
  {
    id: 'true-multisystem-ambiguity',
    spec: { region: 'lower-abdomen', concern: 'skin-change', age: 34, sex: 'female' },
    script: {
      'intake-skin-associated-detail': 'itchy-raised',
      'intake-history-current-impact': '3',
      'intake-skin-duration': 'keeps-returning',
      'intake-lower-associated-system': 'urinary',
      'intake-skin-treatment': 'unsure',
      'intake-skin-features': 'widespread',
      'intake-lower-urinary-detail': 'difficulty',
      'intake-lower-urinary-pattern': 'incomplete-emptying',
    },
    expect: { status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback', fallbackReason: 'TRUE_MULTISYSTEM_AMBIGUITY' },
  },
  {
    id: 'calibration-limited-r1',
    spec: { region: 'chest', concern: 'breathing', age: 45, sex: 'male' },
    // Keep every source-backed discriminator negative so this measures the
    // unchanged R1 calibration gap instead of accidentally satisfying the new
    // Respiratory Medicine gate through the walker's first-option default.
    script: {
      'intake-history-symptom-character': 'unsure',
      'shortness-of-breath-ankle-swelling': 'no',
      'shortness-of-breath-cough': 'no',
      'shortness-of-breath-night-variation': 'no',
      'shortness-of-breath-palpitations': 'no',
      'shortness-of-breath-lying-flat': 'no',
      'shortness-of-breath-wheeze': 'no',
      'intake-breathing-infections': 'no',
      'intake-breathing-phlegm': 'no',
      'intake-breathing-ankles': 'no',
      'intake-breathing-lying-flat': 'no',
      'intake-breathing-activity': 'no',
    },
    expect: {
      status: 'route', specialtyId: 'general-medicine', routeType: 'parent-fallback',
      fallbackReason: 'INSUFFICIENT_SUPPORTED_EVIDENCE', calibration: 'SPECIALTY_EVIDENCE_CALIBRATION_REQUIRED',
    },
  },
  {
    id: 'adolescent-lower-abdomen-no-reproductive-branch',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 15, sex: 'female', reporter: 'young-person' },
    script: {},
    expect: { status: 'route', specialtyId: 'paediatrics', routeType: 'parent-fallback' },
  },
];

/**
 * The nine safety-interruption scenarios. Only a validated hard-stop rule may
 * leave the questionnaire; every other safety-positive answer continues to a
 * clinical direction and shows as urgent clinical review on the result.
 */
export const SAFETY_TRACES: readonly (NamedTrace & { expect: { surface: 'result' | 'priority'; specialtyId?: string; urgentRuleIds?: readonly string[]; hardStopRuleId?: string } })[] = [
  {
    id: 'S1-one-urgent-answer',
    title: 'Age 10, one urgent-but-continuable answer (very painful throat)',
    spec: { region: 'neck', concern: 'throat', age: 10 },
    ui: { dob: '15/01/2016', sex: 'Female', region: 'Neck', concern: 'Sore throat' },
    script: { 'safety-throat-urgent': 'yes' },
    expect: { surface: 'result', specialtyId: 'paediatrics', urgentRuleIds: ['throat-urgent-review'] },
  },
  {
    id: 'S2-two-urgent-findings',
    title: 'Age 8, two different urgent findings (dehydration and dark or bloody stool)',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 8, sex: 'male' },
    ui: { dob: '15/01/2018', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: { 'intake-lower-bowel-detail': 'blood', 'safety-pediatric-dehydration': 'yes', 'safety-rectal-bleeding-urgent': 'yes' },
    expect: { surface: 'result', specialtyId: 'paediatrics', urgentRuleIds: ['pediatric-dehydration-urgent', 'rectal-bleeding-urgent'] },
  },
  {
    id: 'S3-multiple-serious-not-hard-stop',
    title: 'Adult, several serious findings that meet no hard-stop rule',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 50, sex: 'male' },
    ui: { dob: '15/01/1976', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: {
      'intake-lower-bowel-detail': 'blood',
      'intake-lower-bowel-persistence': 'not-improving',
      'intake-lower-bowel-bleeding-duration': 'three-weeks-plus',
      'safety-rectal-bleeding-urgent': 'yes',
    },
    expect: { surface: 'result', specialtyId: 'medical-gastroenterology', urgentRuleIds: ['rectal-bleeding-urgent'] },
  },
  {
    id: 'S4-urgent-ent',
    title: 'Age 10, recurrent sore throats with an urgent answer: ENT plus urgent review',
    spec: { region: 'neck', concern: 'throat', age: 10 },
    ui: { dob: '15/01/2016', sex: 'Female', region: 'Neck', concern: 'Sore throat' },
    script: { 'intake-throat-recurrence': 'seven-in-year', 'intake-throat-impact': 'yes', 'safety-throat-urgent': 'yes' },
    expect: { surface: 'result', specialtyId: 'otorhinolaryngology', urgentRuleIds: ['throat-urgent-review'] },
  },
  {
    id: 'S5-urgent-rectal-bleeding',
    title: 'Adult, dark or bloody stool (urgent, continues)',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 55, sex: 'male' },
    ui: { dob: '15/01/1971', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: { 'intake-lower-bowel-detail': 'blood', 'safety-rectal-bleeding-urgent': 'yes' },
    expect: { surface: 'result', specialtyId: 'medical-gastroenterology', urgentRuleIds: ['rectal-bleeding-urgent'] },
  },
  {
    id: 'S6-heavy-bleeding-hard-stop',
    title: 'Adult, non-stop or heavy bleeding from the bottom (hard stop)',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 55, sex: 'male' },
    ui: { dob: '15/01/1971', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: { 'intake-lower-bowel-detail': 'blood', 'safety-rectal-bleeding-heavy': 'yes' },
    expect: { surface: 'priority', hardStopRuleId: 'rectal-bleeding-heavy' },
  },
  {
    id: 'S7-stroke-pattern-hard-stop',
    title: 'Adult, sudden one-sided weakness, speech or vision change (hard stop)',
    spec: { region: 'face', face: 'patient-left-cheek', concern: 'weakness-drooping', age: 60, sex: 'male' },
    ui: { dob: '15/01/1966', sex: 'Male', region: 'Face', faceRegion: 'patient-left-cheek', concern: 'Weakness or drooping' },
    script: { 'safety-generic-new-neurological-change': 'yes' },
    expect: { surface: 'priority', hardStopRuleId: 'generic-new-neurological-change' },
  },
  {
    id: 'S8-child-immediate-danger',
    title: 'Age 3, a fit or not responding (IMNCI danger sign, hard stop)',
    spec: { region: 'upper-abdomen', concern: 'pain', age: 3, sex: 'male' },
    ui: { dob: '15/01/2023', sex: 'Male', region: 'Upper abdomen', concern: 'Pain or discomfort' },
    script: { 'safety-pediatric-unresponsive-or-seizure': 'yes' },
    expect: { surface: 'priority', hardStopRuleId: 'pediatric-seizure-or-unresponsive' },
  },
  {
    id: 'S9-child-urgent-not-immediate',
    title: 'Age 3, breathing faster than usual (urgent, continues to Paediatrics)',
    spec: { region: 'chest', concern: 'breathing', age: 3, sex: 'male' },
    ui: { dob: '15/01/2023', sex: 'Male', region: 'Chest', concern: 'Breathing difficulty' },
    script: { 'intake-breathing-detail': 'fast', 'safety-pediatric-fast-breathing': 'yes' },
    expect: { surface: 'result', specialtyId: 'paediatrics', urgentRuleIds: ['pediatric-fast-breathing'] },
  },
];

/**
 * The routing reconciliation scenarios (A to T). Each proves one acceptance
 * condition: a coherent pattern reaches the narrower service its published
 * criteria name, children reach shared services, parent services are named
 * conclusions, a secondary location is evidence, only a hard stop interrupts,
 * and two concerns at one location are different interviews.
 */
export const RECONCILIATION_TRACES: readonly (NamedTrace & { expect: { surface: 'result' | 'priority'; specialtyId?: string; hardStopRuleId?: string; urgent?: boolean } })[] = [
  {
    id: 'A-adult-constipation',
    title: 'A. Adult lower abdomen, bowel change, a constipation pattern that keeps coming back',
    spec: { region: 'lower-abdomen', concern: 'bowel-change', age: 50, sex: 'male' },
    ui: { dob: '15/01/1976', sex: 'Male', region: 'Lower abdomen', concern: 'Bowel change' },
    script: {
      'intake-lower-bowel-detail': 'constipation',
      'intake-lower-bowel-persistence': 'regularly-recurrent',
      'intake-lower-bowel-treatment': 'not-helped',
      'intake-lower-bowel-alarm-feature': 'sudden-change',
      'intake-lower-bowel-habit-duration': 'three-weeks-plus',
    },
    expect: { surface: 'result', specialtyId: 'medical-gastroenterology' },
  },
  {
    id: 'B-adult-pelvic-bleeding',
    title: 'B. Adult lower abdomen, a coherent reproductive pattern (bleeding between periods)',
    spec: { region: 'lower-abdomen', concern: 'reproductive-pelvic-change', age: 34, sex: 'female' },
    ui: { dob: '15/01/1992', sex: 'Female', region: 'Lower abdomen', concern: 'Pelvic or reproductive change' },
    script: { 'intake-lower-reproductive-detail': 'bleeding', 'intake-lower-reproductive-timing': 'between-periods', 'intake-lower-pregnancy-context': 'no' },
    expect: { surface: 'result', specialtyId: 'obstetrics-gynaecology' },
  },
  {
    id: 'C-adult-ear',
    title: 'C. Adult ear pain with discharge and hearing change that keeps coming back',
    spec: { region: 'face', face: 'patient-left-ear', concern: 'pain', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Face', faceRegion: 'patient-left-ear', concern: 'Pain or discomfort' },
    script: { 'intake-face-ear-detail': 'inside', 'intake-face-laterality': 'this-side', 'intake-face-ear-persistence': 'recurrent', 'intake-face-ear-associated': 'hearing+discharge' },
    expect: { surface: 'result', specialtyId: 'otorhinolaryngology' },
  },
  {
    id: 'D-adult-nose',
    title: 'D. Adult nose, blocked for more than 3 months',
    spec: { region: 'face', face: 'nose', concern: 'nose-change', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Face', faceRegion: 'nose', concern: 'Blocked, runny or smell change' },
    script: { 'intake-face-nose-detail': 'blocked', 'intake-face-nose-persistence': 'over-three-months' },
    expect: { surface: 'result', specialtyId: 'otorhinolaryngology' },
  },
  {
    id: 'E-adult-knee-injury',
    title: 'E. Adult knee injury: a twist, limping, giving way, for weeks',
    spec: { region: 'left-knee', concern: 'injury', age: 30, sex: 'male' },
    ui: { dob: '15/01/1996', sex: 'Male', region: 'Left knee', concern: 'Injury' },
    script: { 'intake-injury-associated-detail': 'twist', 'intake-injury-function': 'limping', 'intake-msk-duration': 'two-to-six-weeks', 'intake-msk-mechanical': 'gives-way' },
    expect: { surface: 'result', specialtyId: 'orthopaedics' },
  },
  {
    id: 'F-adult-leg-swelling',
    title: 'F. Adult lower leg, a swelling that is growing and has lasted more than 6 weeks',
    spec: { region: 'left-lower-leg', concern: 'swelling-lump', age: 45, sex: 'female' },
    ui: { dob: '15/01/1981', sex: 'Female', region: 'Left lower leg', concern: 'Swelling or a lump' },
    script: { 'intake-swelling-associated-detail': 'growing', 'intake-swelling-duration': 'over-six-weeks' },
    expect: { surface: 'result', specialtyId: 'orthopaedics' },
  },
  {
    id: 'G-adult-chest-spread',
    title: 'G. Adult chest pain on exertion, settling with rest, also felt in the left arm',
    spec: { region: 'chest', concern: 'pain', age: 58, sex: 'male' },
    ui: { dob: '15/01/1968', sex: 'Male', region: 'Chest', concern: 'Pain or discomfort' },
    script: { 'intake-chest-pain-character': 'tight-heavy', 'intake-chest-pain-trigger': 'exertion', 'intake-chest-pain-relief': 'rest-minutes', 'intake-associated-location': 'left-upper-arm' },
    expect: { surface: 'result', specialtyId: 'cardiology' },
  },
  {
    id: 'H-adult-upper-gi',
    title: 'H. Adult upper abdomen, burning linked to meals most days, pharmacy medicines not helping',
    spec: { region: 'upper-abdomen', concern: 'pain', age: 45, sex: 'female' },
    ui: { dob: '15/01/1981', sex: 'Female', region: 'Upper abdomen', concern: 'Pain or discomfort' },
    script: {
      'intake-history-symptom-character': 'burning',
      'intake-upper-gi-frequency': 'most-days',
      'intake-history-current-impact': '2',
      'intake-history-onset': 'gradual',
      'upper-abdominal-pain-exertional': 'no',
      'upper-abdominal-pain-meal-relation': 'yes',
      'upper-abdominal-pain-burning': 'yes',
      'upper-abdominal-pain-nausea-vomiting': 'no',
      'intake-upper-gi-treatment': 'not-helping',
      'intake-upper-gi-alarm': 'none',
    },
    expect: { surface: 'result', specialtyId: 'medical-gastroenterology' },
  },
  {
    id: 'I-child-throat',
    title: 'I. Age 10, repeated disabling sore throats',
    spec: { region: 'neck', concern: 'throat', age: 10, sex: 'female' },
    ui: { dob: '15/01/2016', sex: 'Female', region: 'Neck', concern: 'Sore throat' },
    script: { 'intake-throat-detail': 'sore', 'intake-throat-duration': 'under-one-week', 'intake-throat-associated': 'none', 'intake-throat-recurrence': 'seven-in-year', 'intake-throat-impact': 'yes' },
    expect: { surface: 'result', specialtyId: 'otorhinolaryngology' },
  },
  {
    id: 'J-child-ear',
    title: 'J. Age 7, fluid from the ear for 2 weeks with a hearing change',
    spec: { region: 'face', face: 'patient-right-ear', concern: 'pain', age: 7, sex: 'male' },
    ui: { dob: '15/01/2019', sex: 'Male', region: 'Face', faceRegion: 'patient-right-ear', concern: 'Pain or discomfort' },
    script: { 'intake-pediatric-ear-observation': 'discharge', 'intake-face-laterality': 'this-side', 'intake-face-ear-persistence': 'two-weeks-plus', 'intake-face-ear-associated': 'hearing' },
    expect: { surface: 'result', specialtyId: 'otorhinolaryngology' },
  },
  {
    id: 'K-child-eye',
    title: 'K. Age 6, an eye that turns all the time',
    spec: { region: 'face', face: 'patient-left-eye', concern: 'pain', age: 6, sex: 'female' },
    ui: { dob: '15/01/2020', sex: 'Female', region: 'Face', faceRegion: 'patient-left-eye', concern: 'Pain or discomfort' },
    script: { 'intake-face-eye-detail': 'squint', 'intake-face-laterality': 'this-side', 'intake-face-eye-squint-pattern': 'all-the-time' },
    expect: { surface: 'result', specialtyId: 'ophthalmology' },
  },
  {
    id: 'L-child-arm-injury',
    title: 'L. Age 9, a fall, cannot use the forearm, for weeks',
    spec: { region: 'right-forearm', concern: 'injury', age: 9, sex: 'male' },
    ui: { dob: '15/01/2017', sex: 'Male', region: 'Right forearm', concern: 'Injury' },
    script: { 'intake-injury-associated-detail': 'fall', 'intake-injury-function': 'cannot', 'intake-msk-duration': 'two-to-six-weeks' },
    expect: { surface: 'result', specialtyId: 'orthopaedics' },
  },
  {
    id: 'M-child-skin',
    title: 'M. Age 9, scaly patches for more than 4 weeks, not settling, affecting sleep',
    spec: { region: 'left-forearm', concern: 'skin-change', age: 9, sex: 'female' },
    ui: { dob: '15/01/2017', sex: 'Female', region: 'Left forearm', concern: 'Skin change' },
    script: { 'intake-skin-associated-detail': 'patches', 'intake-skin-duration': 'over-four-weeks', 'intake-skin-treatment': 'not-settled', 'intake-skin-features': 'sleep-life' },
    expect: { surface: 'result', specialtyId: 'dermatology' },
  },
  {
    id: 'N-child-multisystem',
    title: 'N. Age 8, lower tummy pain with feeling generally unwell (multisystem)',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 8, sex: 'female' },
    ui: { dob: '15/01/2018', sex: 'Female', region: 'Lower abdomen', concern: 'Pain or discomfort' },
    script: { 'intake-history-symptom-character': 'cramping', 'intake-associated-location': 'none', 'intake-lower-associated-system': 'systemic' },
    expect: { surface: 'result', specialtyId: 'paediatrics' },
  },
  {
    id: 'O-adult-multisystem',
    title: 'O. Adult lower tummy pain with feeling generally unwell (multisystem)',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 45, sex: 'male' },
    ui: { dob: '15/01/1981', sex: 'Male', region: 'Lower abdomen', concern: 'Pain or discomfort' },
    script: { 'intake-history-symptom-character': 'cramping', 'intake-associated-location': 'none', 'intake-lower-associated-system': 'systemic' },
    expect: { surface: 'result', specialtyId: 'general-medicine' },
  },
  {
    id: 'P-urgent-continues',
    title: 'P. Adult sinus pattern with an urgent (not hard-stop) answer: continues to ENT with urgent review',
    spec: { region: 'face', face: 'nose', concern: 'nose-change', age: 35, sex: 'female' },
    ui: { dob: '15/01/1991', sex: 'Female', region: 'Face', faceRegion: 'nose', concern: 'Blocked, runny or smell change' },
    script: { 'intake-face-nose-detail': 'blocked', 'intake-face-nose-persistence': 'over-three-months', 'safety-sinus-urgent': 'yes' },
    expect: { surface: 'result', specialtyId: 'otorhinolaryngology', urgent: true },
  },
  {
    id: 'Q-hard-stop',
    title: 'Q. Adult palpitations with chest pain or fainting: immediate interruption',
    spec: { region: 'chest', concern: 'palpitations', age: 40, sex: 'female' },
    ui: { dob: '15/01/1986', sex: 'Female', region: 'Chest', concern: 'Heartbeat change' },
    script: { 'intake-palpitation-frequency': 'more-often', 'safety-palpitations-emergency': 'yes' },
    expect: { surface: 'priority', hardStopRuleId: 'palpitations-emergency-features' },
  },
  {
    id: 'R-male-lower-abdomen',
    title: 'R. Adult male lower tummy pain with a urinary pattern: no reproductive question anywhere',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 40, sex: 'male' },
    ui: { dob: '15/01/1986', sex: 'Male', region: 'Lower abdomen', concern: 'Pain or discomfort' },
    script: { 'intake-history-symptom-character': 'cramping', 'intake-associated-location': 'none', 'intake-lower-associated-system': 'urinary', 'intake-lower-urinary-detail': 'blood', 'intake-lower-urinary-pattern': 'recurrent' },
    expect: { surface: 'result', specialtyId: 'urology' },
  },
  {
    id: 'S-female-bowel',
    title: 'S. Adult female lower tummy pain with a bowel pattern: never Obstetrics and Gynaecology',
    spec: { region: 'lower-abdomen', concern: 'pain', age: 35, sex: 'female' },
    ui: { dob: '15/01/1991', sex: 'Female', region: 'Lower abdomen', concern: 'Pain or discomfort' },
    script: { 'intake-history-symptom-character': 'cramping', 'intake-associated-location': 'none', 'intake-lower-associated-system': 'bowel', 'intake-lower-bowel-detail': 'constipation', 'intake-lower-bowel-persistence': 'regularly-recurrent', 'intake-lower-bowel-alarm-feature': 'weight-loss' },
    expect: { surface: 'result', specialtyId: 'medical-gastroenterology' },
  },
  {
    id: 'T1-knee-pain',
    title: 'T1. Adult knee, pain (the weighted joint pain interview)',
    spec: { region: 'left-knee', concern: 'pain', age: 34, sex: 'male' },
    ui: { dob: '15/01/1992', sex: 'Male', region: 'Left knee', concern: 'Pain or discomfort' },
    script: { 'intake-history-symptom-character': 'aching', 'intake-msk-duration': 'over-six-weeks', 'joint-musculoskeletal-pain-use-weight': 'yes' },
    expect: { surface: 'result', specialtyId: 'orthopaedics' },
  },
  {
    id: 'T2-knee-movement',
    title: 'T2. Adult knee, movement or function (a different interview at the same location)',
    spec: { region: 'left-knee', concern: 'movement-function', age: 34, sex: 'male' },
    ui: { dob: '15/01/1992', sex: 'Male', region: 'Left knee', concern: 'Movement or function' },
    script: { 'intake-movement-detail': 'stairs', 'intake-injury-function': 'painful', 'intake-msk-duration': 'over-six-weeks', 'intake-msk-mechanical': 'locks' },
    expect: { surface: 'result', specialtyId: 'orthopaedics' },
  },
  {
    id: 'U-adult-progressive-weakness',
    title: 'U. Adult arm weakness gradually getting worse over weeks, affecting grip (NICE NG127)',
    spec: { region: 'left-upper-arm', concern: 'weakness-drooping', age: 55, sex: 'male' },
    ui: { dob: '15/01/1971', sex: 'Male', region: 'Left upper arm', concern: 'Weakness or drooping' },
    script: { 'intake-neurologic-associated-detail': 'function', 'intake-neurologic-course': 'gradual', 'intake-movement-detail': 'grip', 'safety-neuro-rapidly-progressive': 'no', 'intake-neurologic-associated-features': 'none' },
    expect: { surface: 'result', specialtyId: 'neurology' },
  },
];
