import type { RedFlagRule, SafetyCondition } from './types.ts';
import { ALL_COVERAGE_COMPLAINT_IDS, GENERIC_ADULT_COMPLAINT_IDS } from '../coverage-complaints.ts';
import { SAFETY_VERSION } from './version.ts';
import { INDIA_EMERGENCY_PAYLOAD_ID, URGENT_ASSESSMENT_PAYLOAD_ID } from './payloads.ts';
import {
  AHA_CHEST_PAIN_SAFETY_SOURCE_ID,
  AHA_WARNING_SIGNS_SOURCE_ID,
  NHS_ARTHRITIS_SAFETY_SOURCE_ID,
  NHS_BREATHLESSNESS_SAFETY_SOURCE_ID,
  NHS_HEADACHE_SAFETY_SOURCE_ID,
  NHS_JOINT_PAIN_SAFETY_SOURCE_ID,
  NICE_HEADACHE_SAFETY_SOURCE_ID,
  NHS_ALLERGY_SAFETY_SOURCE_ID,
  NHS_CHEST_PAIN_SAFETY_SOURCE_ID,
  NHS_EYE_PAIN_SAFETY_SOURCE_ID,
  NHS_PELVIC_PAIN_SAFETY_SOURCE_ID,
  NHS_STROKE_SAFETY_SOURCE_ID,
  NICE_FEVER_CHILD_SAFETY_SOURCE_ID,
  NICE_MENINGITIS_SAFETY_SOURCE_ID,
  NHS_CHILD_EMERGENCY_SAFETY_SOURCE_ID,
  NHS_NOSEBLEED_SAFETY_SOURCE_ID,
  WHO_IMCI_SAFETY_SOURCE_ID,
  NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID,
  NHM_IMNCI_YOUNG_INFANT_SAFETY_SOURCE_ID,
  NHS_SORE_THROAT_SAFETY_SOURCE_ID,
  NHS_TONSILLITIS_SAFETY_SOURCE_ID,
  NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID,
  NHS_CHILD_RASH_SAFETY_SOURCE_ID,
  NHS_SPRAINS_SAFETY_SOURCE_ID,
  NHS_DIARRHOEA_VOMITING_SAFETY_SOURCE_ID,
  NHS_UTI_SAFETY_SOURCE_ID,
  NHS_RECTAL_BLEEDING_SAFETY_SOURCE_ID,
  NHS_SINUSITIS_SAFETY_SOURCE_ID,
  NHS_SHINGLES_SAFETY_SOURCE_ID,
  NHS_PALPITATIONS_SAFETY_SOURCE_ID,
  NICE_NEUROLOGICAL_REFERRAL_SAFETY_SOURCE_ID,
  NHS_BACK_PAIN_SAFETY_SOURCE_ID,
  NHS_SCIATICA_SAFETY_SOURCE_ID,
  NHS_BROKEN_RIBS_SAFETY_SOURCE_ID,
  NHS_EAR_INFECTION_SAFETY_SOURCE_ID,
  NHS_HEAD_INJURY_SAFETY_SOURCE_ID,
  NHS_BROKEN_NOSE_SAFETY_SOURCE_ID,
  NHS_WHIPLASH_SAFETY_SOURCE_ID,
  NHS_DVT_SAFETY_SOURCE_ID,
  NHS_HERNIA_SAFETY_SOURCE_ID,
  NHS_GCA_SAFETY_SOURCE_ID,
  NHS_CELLULITIS_SAFETY_SOURCE_ID,
  NHS_VARICOSE_VEINS_SAFETY_SOURCE_ID,
  NHS_DENTAL_ABSCESS_SAFETY_SOURCE_ID,
} from './sources.ts';

function answerEquals(questionId: string, optionId: string): SafetyCondition {
  return { kind: 'answer_equals', questionId, optionId };
}

function all(...conditions: SafetyCondition[]): SafetyCondition {
  return { kind: 'all', conditions };
}

function any(...conditions: SafetyCondition[]): SafetyCondition {
  return { kind: 'any', conditions };
}

function rule(definition: Omit<RedFlagRule, 'version' | 'enabled' | 'continuationPolicy'>): RedFlagRule {
  return {
    ...definition,
    version: SAFETY_VERSION,
    enabled: true,
    continuationPolicy: definition.severity === 'urgent'
      ? 'may_continue_after_acknowledgement'
      : 'must_stop',
  };
}

export const R3_RED_FLAG_RULES: readonly RedFlagRule[] = [
  rule({
    id: 'upper-abdominal-exertional-associated-warning',
    applicableComplaintIds: ['upper-abdominal-pain'],
    requiredQuestionIds: [
      'upper-abdominal-pain-exertional',
      'upper-abdominal-pain-sweating',
      'upper-abdominal-pain-breathlessness',
    ],
    predicate: all(
      answerEquals('upper-abdominal-pain-exertional', 'yes'),
      any(
        answerEquals('upper-abdominal-pain-sweating', 'yes'),
        answerEquals('upper-abdominal-pain-breathlessness', 'yes'),
      ),
    ),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 10,
    provenanceIds: [AHA_CHEST_PAIN_SAFETY_SOURCE_ID, AHA_WARNING_SIGNS_SOURCE_ID],
  }),
  rule({
    id: 'breathing-severe-inability-to-speak',
    applicableComplaintIds: ['shortness-of-breath'],
    requiredQuestionIds: ['safety-shortness-of-breath-severe'],
    predicate: answerEquals('safety-shortness-of-breath-severe', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 10,
    provenanceIds: [NHS_BREATHLESSNESS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'breathing-pale-blue-grey-skin',
    applicableComplaintIds: ['shortness-of-breath'],
    requiredQuestionIds: ['safety-shortness-of-breath-pale-blue-grey'],
    predicate: answerEquals('safety-shortness-of-breath-pale-blue-grey', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_BREATHLESSNESS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'breathing-sudden-confusion',
    applicableComplaintIds: ['shortness-of-breath'],
    requiredQuestionIds: ['safety-shortness-of-breath-sudden-confusion'],
    predicate: answerEquals('safety-shortness-of-breath-sudden-confusion', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 30,
    provenanceIds: [NHS_BREATHLESSNESS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'breathing-coughing-blood',
    applicableComplaintIds: ['shortness-of-breath'],
    requiredQuestionIds: ['safety-shortness-of-breath-coughing-blood'],
    predicate: answerEquals('safety-shortness-of-breath-coughing-blood', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_BREATHLESSNESS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'headache-sudden-extremely-painful',
    applicableComplaintIds: ['headache'],
    requiredQuestionIds: ['safety-headache-sudden-extremely-painful'],
    predicate: answerEquals('safety-headache-sudden-extremely-painful', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 10,
    provenanceIds: [NHS_HEADACHE_SAFETY_SOURCE_ID, NICE_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'headache-new-one-sided-weakness',
    applicableComplaintIds: ['headache'],
    requiredQuestionIds: ['safety-headache-new-one-sided-weakness'],
    predicate: answerEquals('safety-headache-new-one-sided-weakness', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_HEADACHE_SAFETY_SOURCE_ID, NICE_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'headache-speech-memory-vision-change',
    applicableComplaintIds: ['headache'],
    requiredQuestionIds: ['safety-headache-speech-memory-vision'],
    predicate: answerEquals('safety-headache-speech-memory-vision', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 30,
    provenanceIds: [NHS_HEADACHE_SAFETY_SOURCE_ID, NICE_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'headache-drowsy-confused',
    applicableComplaintIds: ['headache'],
    requiredQuestionIds: ['safety-headache-drowsy-confused'],
    predicate: answerEquals('safety-headache-drowsy-confused', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_HEADACHE_SAFETY_SOURCE_ID, NICE_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'joint-injury-severe-or-displaced',
    applicableComplaintIds: ['joint-musculoskeletal-pain'],
    requiredQuestionIds: ['joint-musculoskeletal-pain-injury', 'safety-joint-injury-severe-or-displaced'],
    predicate: all(
      answerEquals('joint-musculoskeletal-pain-injury', 'yes'),
      answerEquals('safety-joint-injury-severe-or-displaced', 'yes'),
    ),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 10,
    provenanceIds: [NHS_JOINT_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'joint-injury-sensation-or-circulation-change',
    applicableComplaintIds: ['joint-musculoskeletal-pain'],
    requiredQuestionIds: ['joint-musculoskeletal-pain-injury', 'safety-joint-injury-sensation-circulation'],
    predicate: all(
      answerEquals('joint-musculoskeletal-pain-injury', 'yes'),
      answerEquals('safety-joint-injury-sensation-circulation', 'yes'),
    ),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_JOINT_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'joint-sudden-hot-swollen',
    applicableComplaintIds: ['joint-musculoskeletal-pain', 'musculoskeletal-concern'],
    requiredQuestionIds: ['safety-joint-sudden-hot-swollen'],
    predicate: answerEquals('safety-joint-sudden-hot-swollen', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 30,
    provenanceIds: [NHS_JOINT_PAIN_SAFETY_SOURCE_ID, NHS_ARTHRITIS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'generic-severe-breathing',
    applicableComplaintIds: GENERIC_ADULT_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-generic-severe-breathing'],
    predicate: answerEquals('safety-generic-severe-breathing', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 10,
    provenanceIds: [NHS_BREATHLESSNESS_SAFETY_SOURCE_ID, NHS_ALLERGY_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'generic-new-neurological-change',
    // Kept in step with NEUROLOGIC_GENERIC_COMPLAINTS in questions.ts, which
    // explains why the ear family is in scope. Predicate, severity, payload
    // and provenance are unchanged.
    applicableComplaintIds: [
      'face-eye-concern',
      'face-ear-concern',
      'face-neurologic-concern',
      'regional-neurologic-concern',
      'neck-concern',
      'general-region-concern',
    ],
    requiredQuestionIds: ['safety-generic-new-neurological-change'],
    predicate: answerEquals('safety-generic-new-neurological-change', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_STROKE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'generic-unresponsive-or-seizure',
    applicableComplaintIds: GENERIC_ADULT_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-generic-unresponsive-or-seizure'],
    predicate: answerEquals('safety-generic-unresponsive-or-seizure', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 30,
    provenanceIds: [NHS_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'lower-abdominal-severe-or-faint',
    applicableComplaintIds: ['lower-abdominal-pelvic-concern', 'lower-abdominal-reproductive-concern'],
    requiredQuestionIds: ['safety-lower-abdominal-severe-or-faint'],
    predicate: answerEquals('safety-lower-abdominal-severe-or-faint', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_PELVIC_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'lower-abdominal-heavy-bleeding',
    applicableComplaintIds: ['lower-abdominal-reproductive-concern'],
    requiredQuestionIds: ['safety-lower-abdominal-heavy-bleeding'],
    predicate: answerEquals('safety-lower-abdominal-heavy-bleeding', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHS_PELVIC_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'eye-sudden-vision-loss-or-injury',
    applicableComplaintIds: ['face-eye-concern'],
    requiredQuestionIds: ['safety-eye-sudden-vision-loss-or-injury'],
    predicate: answerEquals('safety-eye-sudden-vision-loss-or-injury', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_EYE_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'nosebleed-prolonged-or-excessive',
    applicableComplaintIds: ['face-nose-concern'],
    requiredQuestionIds: ['safety-nosebleed-prolonged-or-excessive'],
    predicate: answerEquals('safety-nosebleed-prolonged-or-excessive', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 30,
    provenanceIds: [NHS_NOSEBLEED_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'chest-persistent-spreading-associated',
    applicableComplaintIds: ['chest-concern'],
    requiredQuestionIds: ['safety-chest-persistent-spreading-associated'],
    predicate: answerEquals('safety-chest-persistent-spreading-associated', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_CHEST_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'skin-airway-swelling',
    applicableComplaintIds: ['regional-skin-concern', 'face-general-concern', 'face-oral-jaw-concern', 'neck-concern', 'throat-concern'],
    requiredQuestionIds: ['safety-skin-airway-swelling'],
    predicate: answerEquals('safety-skin-airway-swelling', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_ALLERGY_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'neck-meningitis-warning-pattern',
    applicableComplaintIds: ['neck-concern'],
    requiredQuestionIds: ['safety-neck-meningitis-warning-pattern'],
    predicate: answerEquals('safety-neck-meningitis-warning-pattern', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NICE_MENINGITIS_SAFETY_SOURCE_ID],
  }),
  /*
    The paediatric rules below are applicable to every coverage family because
    a child now keeps their anatomy and concern. contextual-safety.ts decides
    which of their questions a given child is asked; an unasked question can
    never satisfy a predicate.
  */
  /*
    One rule per danger sign, each read from exactly one question, so an
    interruption always names the sign that was reported. These replace a
    combined "general danger sign" rule that fired on any one of three
    questions and could not say which. The signs, and their level, are the
    sources' own: IMNCI and WHO IMCI treat each as a general danger sign
    needing urgent referral, and NHS names struggling to breathe, a fit, and a
    child who cannot be woken as reasons to call 999.
  */
  rule({
    id: 'pediatric-struggling-to-breathe',
    applicableComplaintIds: ALL_COVERAGE_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-pediatric-severe-breathing'],
    predicate: answerEquals('safety-pediatric-severe-breathing', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 8,
    provenanceIds: [NHS_CHILD_EMERGENCY_SAFETY_SOURCE_ID, NHS_BREATHLESSNESS_SAFETY_SOURCE_ID, NICE_FEVER_CHILD_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-seizure-or-unresponsive',
    applicableComplaintIds: ALL_COVERAGE_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-pediatric-unresponsive-or-seizure'],
    predicate: answerEquals('safety-pediatric-unresponsive-or-seizure', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 9,
    provenanceIds: [
      WHO_IMCI_SAFETY_SOURCE_ID,
      NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID,
      NHS_CHILD_EMERGENCY_SAFETY_SOURCE_ID,
      NICE_FEVER_CHILD_SAFETY_SOURCE_ID,
    ],
  }),
  rule({
    id: 'pediatric-unable-to-drink-or-vomits-everything',
    applicableComplaintIds: ALL_COVERAGE_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-pediatric-under-five-feeding-vomiting'],
    predicate: answerEquals('safety-pediatric-under-five-feeding-vomiting', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 11,
    provenanceIds: [WHO_IMCI_SAFETY_SOURCE_ID, NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-sudden-neurological-change',
    applicableComplaintIds: ALL_COVERAGE_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-pediatric-sudden-neurological-change'],
    predicate: answerEquals('safety-pediatric-sudden-neurological-change', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_STROKE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'infant-serious-illness-sign',
    applicableComplaintIds: ALL_COVERAGE_COMPLAINT_IDS,
    requiredQuestionIds: ['safety-infant-serious-illness'],
    predicate: answerEquals('safety-infant-serious-illness', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 12,
    provenanceIds: [NHM_IMNCI_YOUNG_INFANT_SAFETY_SOURCE_ID, NICE_FEVER_CHILD_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-chest-indrawing-or-stridor',
    applicableComplaintIds: ['chest-breathing-concern', 'chest-concern'],
    requiredQuestionIds: ['safety-pediatric-chest-indrawing-or-stridor'],
    predicate: answerEquals('safety-pediatric-chest-indrawing-or-stridor', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 14,
    provenanceIds: [NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'throat-airway-danger',
    applicableComplaintIds: ['throat-concern', 'neck-concern', 'face-oral-jaw-concern'],
    requiredQuestionIds: ['safety-throat-airway'],
    predicate: answerEquals('safety-throat-airway', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 10,
    provenanceIds: [NHS_SORE_THROAT_SAFETY_SOURCE_ID, NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID],
  }),
  rule({
    // PENDING CLINICAL REVIEW: NHS Dental abscess and Toothache, 999 or A&E.
    id: 'dental-spreading-swelling',
    applicableComplaintIds: ['face-oral-jaw-concern', 'face-general-concern'],
    requiredQuestionIds: ['safety-dental-spreading-swelling'],
    predicate: answerEquals('safety-dental-spreading-swelling', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 11,
    provenanceIds: [NHS_DENTAL_ABSCESS_SAFETY_SOURCE_ID],
  }),
  /* --- Questionnaire expansion phase 2 (PENDING CLINICAL REVIEW) ----------- */
  rule({
    id: 'dvt-breathless-or-chest-pain',
    applicableComplaintIds: ['musculoskeletal-concern', 'regional-skin-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-dvt-one-leg', 'safety-dvt-breathless-chest'],
    predicate: all(answerEquals('safety-dvt-one-leg', 'yes'), answerEquals('safety-dvt-breathless-chest', 'yes')),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 12,
    provenanceIds: [NHS_DVT_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'skin-infection-emergency-features',
    applicableComplaintIds: ['regional-skin-concern', 'face-general-concern'],
    requiredQuestionIds: ['safety-skin-hot-swollen', 'safety-skin-infection-emergency'],
    predicate: all(answerEquals('safety-skin-hot-swollen', 'yes'), answerEquals('safety-skin-infection-emergency', 'yes')),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 12,
    provenanceIds: [NHS_CELLULITIS_SAFETY_SOURCE_ID],
  }),
  // Phase 3: head, face, nose and neck injury (NHS, PENDING CLINICAL REVIEW).
  rule({
    id: 'head-injury-emergency-signs',
    applicableComplaintIds: ['general-region-concern', 'face-general-concern', 'face-nose-concern', 'face-eye-concern', 'face-ear-concern', 'face-oral-jaw-concern', 'head-concern'],
    requiredQuestionIds: ['safety-head-injury-signs'],
    predicate: answerEquals('safety-head-injury-signs', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 11,
    provenanceIds: [NHS_HEAD_INJURY_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'head-injury-emergency-mechanism',
    applicableComplaintIds: ['general-region-concern', 'face-general-concern', 'face-nose-concern', 'face-eye-concern', 'face-ear-concern', 'face-oral-jaw-concern', 'head-concern'],
    requiredQuestionIds: ['safety-head-injury-mechanism'],
    predicate: answerEquals('safety-head-injury-mechanism', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 11,
    provenanceIds: [NHS_HEAD_INJURY_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'nose-injury-emergency',
    applicableComplaintIds: ['face-nose-concern'],
    requiredQuestionIds: ['safety-nose-injury-emergency'],
    predicate: answerEquals('safety-nose-injury-emergency', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 12,
    provenanceIds: [NHS_BROKEN_NOSE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'head-injury-urgent',
    applicableComplaintIds: ['general-region-concern', 'face-general-concern', 'face-nose-concern', 'face-eye-concern', 'face-ear-concern', 'face-oral-jaw-concern', 'head-concern'],
    requiredQuestionIds: ['safety-head-injury-urgent'],
    predicate: answerEquals('safety-head-injury-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_HEAD_INJURY_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'neck-injury-urgent',
    applicableComplaintIds: ['neck-concern', 'face-general-concern'],
    requiredQuestionIds: ['safety-neck-injury-urgent'],
    predicate: answerEquals('safety-neck-injury-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_WHIPLASH_SAFETY_SOURCE_ID],
  }),
  // Phase 3 candidate fix for the weighted joint complaint (PENDING CLINICAL REVIEW).
  rule({
    id: 'joint-dvt-breathless-or-chest-pain',
    applicableComplaintIds: ['joint-musculoskeletal-pain'],
    requiredQuestionIds: ['safety-joint-dvt-one-leg', 'safety-joint-dvt-breathless'],
    predicate: all(answerEquals('safety-joint-dvt-one-leg', 'yes'), answerEquals('safety-joint-dvt-breathless', 'yes')),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 12,
    provenanceIds: [NHS_DVT_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'joint-dvt-suspected-urgent',
    applicableComplaintIds: ['joint-musculoskeletal-pain'],
    requiredQuestionIds: ['safety-joint-dvt-one-leg'],
    predicate: answerEquals('safety-joint-dvt-one-leg', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_DVT_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'joint-back-urgent-features',
    applicableComplaintIds: ['joint-musculoskeletal-pain'],
    requiredQuestionIds: ['safety-joint-back-urgent'],
    predicate: answerEquals('safety-joint-back-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_BACK_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'dvt-suspected-urgent',
    applicableComplaintIds: ['musculoskeletal-concern', 'regional-skin-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-dvt-one-leg'],
    predicate: answerEquals('safety-dvt-one-leg', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_DVT_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'hernia-complication-urgent',
    applicableComplaintIds: ['general-region-concern', 'lower-abdominal-pelvic-concern', 'upper-abdominal-concern'],
    requiredQuestionIds: ['safety-hernia-complication'],
    predicate: answerEquals('safety-hernia-complication', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_HERNIA_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'temporal-arteritis-urgent',
    applicableComplaintIds: ['face-general-concern'],
    requiredQuestionIds: ['safety-gca-features'],
    predicate: answerEquals('safety-gca-features', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_GCA_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'back-urgent-features',
    applicableComplaintIds: ['musculoskeletal-concern'],
    requiredQuestionIds: ['safety-back-urgent'],
    predicate: answerEquals('safety-back-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_BACK_PAIN_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'skin-painful-hot-swollen-urgent',
    applicableComplaintIds: ['regional-skin-concern', 'face-general-concern'],
    requiredQuestionIds: ['safety-skin-hot-swollen'],
    predicate: answerEquals('safety-skin-hot-swollen', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_CELLULITIS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'varicose-vein-bleeding-urgent',
    applicableComplaintIds: ['musculoskeletal-concern', 'regional-skin-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-varicose-bleeding'],
    predicate: answerEquals('safety-varicose-bleeding', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 56,
    provenanceIds: [NHS_VARICOSE_VEINS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-headache-sudden-or-recent-injury',
    applicableComplaintIds: ['head-concern'],
    requiredQuestionIds: ['safety-pediatric-headache-sudden-or-injury'],
    predicate: answerEquals('safety-pediatric-headache-sudden-or-injury', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 16,
    provenanceIds: [NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-fever-stiff-neck-or-rash',
    applicableComplaintIds: ['head-concern', 'regional-skin-concern', 'neck-concern', 'face-general-concern'],
    requiredQuestionIds: ['safety-pediatric-fever-stiff-neck-rash'],
    predicate: answerEquals('safety-pediatric-fever-stiff-neck-rash', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 16,
    provenanceIds: [NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID, NHS_CHILD_RASH_SAFETY_SOURCE_ID, NICE_MENINGITIS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-injury-emergency',
    applicableComplaintIds: ['musculoskeletal-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-pediatric-injury-emergency'],
    predicate: answerEquals('safety-pediatric-injury-emergency', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_JOINT_PAIN_SAFETY_SOURCE_ID, NHS_SPRAINS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-abdominal-emergency',
    applicableComplaintIds: ['upper-abdominal-concern', 'lower-abdominal-pelvic-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-pediatric-abdominal-emergency'],
    predicate: answerEquals('safety-pediatric-abdominal-emergency', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 20,
    provenanceIds: [NHS_DIARRHOEA_VOMITING_SAFETY_SOURCE_ID],
  }),
  /*
    Tender swelling behind the ear has two stated levels of action, so it is
    two questions with the same wording, enabled per age band in
    contextual-safety.ts. Government of India IMNCI classifies it in a child
    under five as needing urgent referral; NHS names swelling around the ear
    as an urgent, not emergency, reason to be seen at any other age.
  */
  rule({
    id: 'pediatric-under-five-swelling-behind-ear',
    applicableComplaintIds: ['face-ear-concern'],
    requiredQuestionIds: ['safety-pediatric-under-five-ear-swelling'],
    predicate: answerEquals('safety-pediatric-under-five-ear-swelling', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 30,
    provenanceIds: [NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID],
  }),
  /* --- Urgent: recorded, the interview continues ----------------------- */
  rule({
    id: 'ear-swelling-around-ear-urgent',
    applicableComplaintIds: ['face-ear-concern'],
    requiredQuestionIds: ['safety-ear-swelling-behind-ear'],
    predicate: answerEquals('safety-ear-swelling-behind-ear', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 60,
    provenanceIds: [NHS_EAR_INFECTION_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-fast-breathing',
    applicableComplaintIds: ['chest-breathing-concern', 'chest-concern'],
    requiredQuestionIds: ['safety-pediatric-fast-breathing'],
    predicate: answerEquals('safety-pediatric-fast-breathing', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'throat-urgent-review',
    applicableComplaintIds: ['throat-concern', 'neck-concern', 'face-oral-jaw-concern'],
    requiredQuestionIds: ['safety-throat-urgent'],
    predicate: answerEquals('safety-throat-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHS_SORE_THROAT_SAFETY_SOURCE_ID, NHS_TONSILLITIS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-headache-urgent-features',
    applicableComplaintIds: ['head-concern'],
    requiredQuestionIds: ['safety-pediatric-headache-urgent'],
    predicate: answerEquals('safety-pediatric-headache-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'injury-worsening-urgent',
    applicableComplaintIds: ['musculoskeletal-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-injury-worsening'],
    predicate: answerEquals('safety-injury-worsening', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 55,
    provenanceIds: [NHS_SPRAINS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'pediatric-dehydration-urgent',
    applicableComplaintIds: ['upper-abdominal-concern', 'lower-abdominal-pelvic-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-pediatric-dehydration'],
    predicate: answerEquals('safety-pediatric-dehydration', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHS_DIARRHOEA_VOMITING_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'urinary-unwell-urgent',
    applicableComplaintIds: ['upper-abdominal-concern', 'lower-abdominal-pelvic-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-urinary-unwell'],
    predicate: answerEquals('safety-urinary-unwell', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHS_UTI_SAFETY_SOURCE_ID],
  }),
  /*
    Rectal bleeding has three levels in its source, and only the first is an
    emergency. Other reported blood is a routine GP matter: it is characterized
    by the bowel branch and weighed by the gastroenterology criteria, never
    escalated here.
  */
  rule({
    id: 'rectal-bleeding-heavy',
    applicableComplaintIds: ['upper-abdominal-concern', 'lower-abdominal-pelvic-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-rectal-bleeding-heavy'],
    predicate: answerEquals('safety-rectal-bleeding-heavy', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 38,
    provenanceIds: [NHS_RECTAL_BLEEDING_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'rectal-bleeding-urgent',
    applicableComplaintIds: ['upper-abdominal-concern', 'lower-abdominal-pelvic-concern', 'general-region-concern'],
    requiredQuestionIds: ['safety-rectal-bleeding-urgent'],
    predicate: answerEquals('safety-rectal-bleeding-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 50,
    provenanceIds: [NHS_RECTAL_BLEEDING_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'sinus-urgent-review',
    applicableComplaintIds: ['face-nose-concern'],
    requiredQuestionIds: ['safety-sinus-urgent'],
    predicate: answerEquals('safety-sinus-urgent', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 52,
    provenanceIds: [NHS_SINUSITIS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'face-rash-eye-nose-urgent',
    applicableComplaintIds: ['face-neurologic-concern', 'face-general-concern'],
    requiredQuestionIds: ['safety-face-rash-eye-nose'],
    predicate: answerEquals('safety-face-rash-eye-nose', 'yes'),
    severity: 'urgent',
    payloadId: URGENT_ASSESSMENT_PAYLOAD_ID,
    priority: 52,
    provenanceIds: [NHS_SHINGLES_SAFETY_SOURCE_ID],
  }),
  /* Routing reconciliation: one exact-predicate emergency rule per new branch. */
  rule({
    id: 'palpitations-emergency-features',
    applicableComplaintIds: ['chest-concern'],
    requiredQuestionIds: ['safety-palpitations-emergency'],
    predicate: answerEquals('safety-palpitations-emergency', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 40,
    provenanceIds: [NHS_PALPITATIONS_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'neuro-rapidly-progressive-weakness',
    applicableComplaintIds: ['regional-neurologic-concern', 'neck-concern', 'face-neurologic-concern'],
    requiredQuestionIds: ['safety-neuro-rapidly-progressive'],
    predicate: answerEquals('safety-neuro-rapidly-progressive', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 15,
    provenanceIds: [NICE_NEUROLOGICAL_REFERRAL_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'back-cauda-equina-pattern',
    applicableComplaintIds: ['musculoskeletal-concern'],
    requiredQuestionIds: ['safety-back-cauda-equina'],
    predicate: answerEquals('safety-back-cauda-equina', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 12,
    provenanceIds: [NHS_BACK_PAIN_SAFETY_SOURCE_ID, NHS_SCIATICA_SAFETY_SOURCE_ID, NICE_NEUROLOGICAL_REFERRAL_SAFETY_SOURCE_ID],
  }),
  rule({
    id: 'upper-abdomen-injury-emergency',
    applicableComplaintIds: ['general-region-concern', 'upper-abdominal-concern', 'chest-concern'],
    requiredQuestionIds: ['safety-upper-abdomen-injury-emergency'],
    predicate: answerEquals('safety-upper-abdomen-injury-emergency', 'yes'),
    severity: 'emergency',
    payloadId: INDIA_EMERGENCY_PAYLOAD_ID,
    priority: 11,
    provenanceIds: [NHS_BROKEN_RIBS_SAFETY_SOURCE_ID],
  }),
];
