import type { ProvenanceSource } from '../data/types.ts';
import type { SafetyEvidenceRegisterEntry } from './types.ts';

export const AHA_CHEST_PAIN_SAFETY_SOURCE_ID = 'r3-aha-acc-chest-pain-guideline-2021';
export const AHA_WARNING_SIGNS_SOURCE_ID = 'r3-aha-heart-attack-warning-signs-2024';
export const NHS_BREATHLESSNESS_SAFETY_SOURCE_ID = 'r3-nhs-shortness-of-breath-2024';
export const NHS_HEADACHE_SAFETY_SOURCE_ID = 'r3-nhs-migraine-emergency-guidance';
export const NICE_HEADACHE_SAFETY_SOURCE_ID = 'r3-nice-cg150-headache-2025';
export const NHS_JOINT_PAIN_SAFETY_SOURCE_ID = 'r3-nhs-joint-pain-2026';
export const NHS_ARTHRITIS_SAFETY_SOURCE_ID = 'r3-nhs-arthritis-urgent-guidance';
export const INDIA_ERSS_SOURCE_ID = 'r3-india-erss-112';
export const NHS_PELVIC_PAIN_SAFETY_SOURCE_ID = 'r3-nhs-pelvic-pain-2026';
export const NHS_EYE_PAIN_SAFETY_SOURCE_ID = 'r3-nhs-eye-pain-2025';
export const NHS_STROKE_SAFETY_SOURCE_ID = 'r3-nhs-stroke-symptoms-2024';
export const NHS_CHEST_PAIN_SAFETY_SOURCE_ID = 'r3-nhs-chest-pain';
export const NHS_ALLERGY_SAFETY_SOURCE_ID = 'r3-nhs-allergy-anaphylaxis';
export const WHO_IMCI_SAFETY_SOURCE_ID = 'r3-who-imci-danger-signs';
export const NICE_FEVER_CHILD_SAFETY_SOURCE_ID = 'r3-nice-ng143-fever-under-five';
export const NICE_MENINGITIS_SAFETY_SOURCE_ID = 'r3-nice-ng240-meningitis';
export const NHS_CHILD_EMERGENCY_SAFETY_SOURCE_ID = 'r3-nhs-child-accident-emergency';
export const NHS_NOSEBLEED_SAFETY_SOURCE_ID = 'r3-nhs-nosebleed';
export const NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID = 'r3-nhm-imnci-module-5-sick-child';
export const NHM_IMNCI_YOUNG_INFANT_SAFETY_SOURCE_ID = 'r3-nhm-f-imnci-chart-booklet';
export const NHS_SORE_THROAT_SAFETY_SOURCE_ID = 'r3-nhs-sore-throat';
export const NHS_TONSILLITIS_SAFETY_SOURCE_ID = 'r3-nhs-tonsillitis';
export const NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID = 'r3-nhs-headaches-in-children';
export const NHS_CHILD_RASH_SAFETY_SOURCE_ID = 'r3-nhs-rashes-babies-children';
export const NHS_SPRAINS_SAFETY_SOURCE_ID = 'r3-nhs-sprains-and-strains';
export const NHS_DIARRHOEA_VOMITING_SAFETY_SOURCE_ID = 'r3-nhs-diarrhoea-and-vomiting';
export const NHS_UTI_SAFETY_SOURCE_ID = 'r3-nhs-urinary-tract-infection';
export const NHS_EAR_INFECTION_SAFETY_SOURCE_ID = 'r3-nhs-ear-infections';
export const NHS_RECTAL_BLEEDING_SAFETY_SOURCE_ID = 'r3-nhs-rectal-bleeding';
export const NHS_SINUSITIS_SAFETY_SOURCE_ID = 'r3-nhs-sinusitis';
export const NHS_SHINGLES_SAFETY_SOURCE_ID = 'r3-nhs-shingles';
export const NHS_PALPITATIONS_SAFETY_SOURCE_ID = 'r3-nhs-heart-palpitations';
export const NICE_NEUROLOGICAL_REFERRAL_SAFETY_SOURCE_ID = 'r3-nice-ng127-neurological-referral';
export const NHS_BACK_PAIN_SAFETY_SOURCE_ID = 'r3-nhs-back-pain';
export const NHS_SCIATICA_SAFETY_SOURCE_ID = 'r3-nhs-sciatica';
export const NHS_BROKEN_RIBS_SAFETY_SOURCE_ID = 'r3-nhs-broken-or-bruised-ribs';

const ACCESSED_AT = '2026-09-10';
/** The research pass that added the paediatric, throat and injury checks. */
const PEDIATRIC_PASS_ACCESSED_AT = '2026-09-23';
/** The normalization pass that added the rectal bleeding, sinus and facial rash checks. */
const NORMALIZATION_PASS_ACCESSED_AT = '2026-09-24';
/** The routing reconciliation pass that added the palpitations, rapidly progressive weakness and back checks. */
const RECONCILIATION_PASS_ACCESSED_AT = '2026-09-25';
/** The clinical blocker pass that added the upper tummy injury check. */
const BLOCKER_PASS_ACCESSED_AT = '2026-09-26';
const PENDING_REVIEW_NOTE =
  'Source-backed prototype pending clinical review. Supports the warning-sign relationship and the stated level of action only; it does not diagnose and does not validate this kiosk.';

export const R3_SAFETY_SOURCES: readonly ProvenanceSource[] = [
  {
    id: AHA_CHEST_PAIN_SAFETY_SOURCE_ID,
    organization: 'American Heart Association and American College of Cardiology',
    title: '2021 Guideline for the Evaluation and Diagnosis of Chest Pain — slide set',
    sourceType: 'clinical_guideline',
    reference: '2021 AHA/ACC Chest Pain Guideline',
    url: 'https://professional.heart.org/-/media/PHD-Files-2/Science-News/2/2021/2021-Chest-Pain-Guideline-Slide-Set-PDF-102821.pdf',
    publicationDate: '2021-10-28',
    accessedAt: ACCESSED_AT,
    locator: 'Top 10 Take-Home Messages; Table 3',
    scope: 'Supports treating upper-abdominal discomfort as a possible anginal equivalent and assessing exertion, dyspnea, diaphoresis, and nausea.',
    notes: 'Does not validate the DocMatch+ compound predicate or establish production safety.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: '2021',
  },
  {
    id: AHA_WARNING_SIGNS_SOURCE_ID,
    organization: 'American Heart Association',
    title: 'Warning Signs of a Heart Attack',
    sourceType: 'professional_society_guidance',
    reference: 'AHA patient warning-sign guidance',
    url: 'https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack',
    sourceUpdatedAt: '2024-12-12',
    accessedAt: ACCESSED_AT,
    locator: 'Warning signs; emergency action',
    scope: 'Supports stomach or upper-body discomfort, shortness of breath, cold sweat, and prompt emergency-service action as warning-sign concepts.',
    notes: 'Does not diagnose a cardiac condition and does not validate this software as a medical device.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2024-12-12',
  },
  {
    id: NHS_BREATHLESSNESS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Shortness of breath',
    sourceType: 'government_guidance',
    reference: 'NHS symptoms guidance',
    url: 'https://www.nhs.uk/symptoms/shortness-of-breath/',
    sourceUpdatedAt: '2024-01-30',
    accessedAt: ACCESSED_AT,
    locator: 'Immediate action and urgent advice',
    scope: 'Supports emergency action for gasping, choking, inability to speak, pale/blue/grey skin, or sudden confusion, and urgent assessment for coughing blood.',
    notes: 'UK service numbers are not copied into India-facing payloads. The source does not validate DocMatch+.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2024-01-30',
  },
  {
    id: NHS_HEADACHE_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Migraine',
    sourceType: 'government_guidance',
    reference: 'NHS conditions guidance',
    url: 'https://www.nhs.uk/conditions/migraine/',
    accessedAt: ACCESSED_AT,
    locator: 'Immediate action required',
    scope: 'Supports emergency action for sudden extremely painful headache, speech or memory problems, vision loss/change, drowsiness/confusion, and one-sided weakness.',
    notes: 'Questions ask observable warning signs and do not assert migraine, stroke, or another diagnosis.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-10',
  },
  {
    id: NICE_HEADACHE_SAFETY_SOURCE_ID,
    organization: 'National Institute for Health and Care Excellence',
    title: 'Headaches in over 12s: diagnosis and management',
    sourceType: 'clinical_guideline',
    reference: 'NICE guideline CG150',
    url: 'https://www.nice.org.uk/guidance/cg150/chapter/recommendations',
    publicationDate: '2012-09-19',
    sourceUpdatedAt: '2025-06-03',
    accessedAt: ACCESSED_AT,
    locator: 'Recommendation 1.1.1',
    scope: 'Supports further evaluation or referral for sudden maximum-intensity headache, new neurological deficit, cognitive dysfunction, or impaired consciousness.',
    notes: 'NICE supports further evaluation; emergency payload action is paired with the more explicit NHS immediate-action guidance.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'updated-2025-06-03',
  },
  {
    id: NHS_JOINT_PAIN_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Joint pain',
    sourceType: 'government_guidance',
    reference: 'NHS symptoms guidance',
    url: 'https://www.nhs.uk/symptoms/joint-pain/',
    sourceUpdatedAt: '2026-02-26',
    accessedAt: ACCESSED_AT,
    locator: 'Urgent advice; immediate action required',
    scope: 'Supports emergency assessment after injury for very severe pain, inability to bear weight, displaced joint, tingling or loss of feeling, and urgent assessment for a hot swollen joint.',
    notes: 'Does not establish a diagnosis or validate all musculoskeletal presentations.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2026-02-26',
  },
  {
    id: NHS_ARTHRITIS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Arthritis',
    sourceType: 'government_guidance',
    reference: 'NHS conditions guidance',
    url: 'https://www.nhs.uk/conditions/arthritis/',
    accessedAt: ACCESSED_AT,
    locator: 'Urgent advice',
    scope: 'Supports urgent assessment for severe single-joint pain and swelling of sudden onset or red/hot skin around a joint.',
    notes: 'Does not diagnose arthritis or determine the eventual specialty destination.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-10',
  },
  {
    id: NHS_PELVIC_PAIN_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Pelvic pain',
    sourceType: 'government_guidance',
    reference: 'NHS symptoms guidance',
    url: 'https://www.nhs.uk/symptoms/pelvic-pain/',
    accessedAt: '2026-09-21',
    locator: 'Urgent advice; immediate action required',
    scope: 'Supports immediate assessment for severe or worsening pelvic pain, pain with movement or touch, faintness or collapse, breathing difficulty, heavy vaginal bleeding or sudden confusion.',
    notes: 'Questions describe warning features and do not infer a pelvic or pregnancy diagnosis.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: NHS_EYE_PAIN_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Eye pain',
    sourceType: 'government_guidance',
    reference: 'NHS symptoms guidance',
    url: 'https://www.nhs.uk/symptoms/eye-pain/',
    sourceUpdatedAt: '2025-10-21',
    accessedAt: '2026-09-21',
    locator: 'Urgent advice; immediate action required',
    scope: 'Supports immediate assessment for sudden loss of vision, a pierced eye, or an object stuck in the eye, and urgent review for severe pain, redness or vision change.',
    notes: 'Does not diagnose an eye condition or make eye location a specialty route.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2025-10-21',
  },
  {
    id: NHS_NOSEBLEED_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Nosebleed',
    sourceType: 'government_guidance',
    reference: 'NHS conditions guidance',
    url: 'https://www.nhs.uk/conditions/nosebleed/',
    sourceUpdatedAt: '2023-12-05',
    accessedAt: '2026-09-21',
    locator: 'Immediate action required',
    scope: 'Supports immediate assessment for bleeding longer than 10 to 15 minutes, excessive bleeding, swallowed blood with vomiting, head injury, weakness or dizziness, or difficulty breathing.',
    notes: 'Does not diagnose the cause of bleeding or make nose location an ENT route.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2023-12-05',
  },
  {
    id: NHS_STROKE_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Symptoms of a stroke',
    sourceType: 'government_guidance',
    reference: 'NHS conditions guidance',
    url: 'https://www.nhs.uk/conditions/stroke/symptoms/',
    sourceUpdatedAt: '2024-09-12',
    accessedAt: '2026-09-21',
    locator: 'Check for signs of a stroke; immediate action required',
    scope: 'Supports immediate action for sudden face or one-sided weakness, speech difficulty, numbness and sudden visual loss.',
    notes: 'The warning-sign question is evidence-triggered and does not infer stroke or a Neurology route from body location.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2024-09-12',
  },
  {
    id: NHS_CHEST_PAIN_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Chest pain',
    sourceType: 'government_guidance',
    reference: 'NHS conditions guidance',
    url: 'https://www.nhs.uk/conditions/chest-pain/',
    accessedAt: '2026-09-21',
    locator: 'Immediate action required',
    scope: 'Supports immediate assessment for sudden chest discomfort that does not go away, spread to the arm, neck, jaw, stomach or back, or associated sweating, sickness, lightheadedness or breathlessness.',
    notes: 'Does not diagnose a heart attack or make chest location a Cardiology route.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: NHS_ALLERGY_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Allergies',
    sourceType: 'government_guidance',
    reference: 'NHS conditions guidance',
    url: 'https://www.nhs.uk/conditions/allergies/',
    accessedAt: '2026-09-21',
    locator: 'Immediate action required',
    scope: 'Supports immediate assessment for sudden lip, mouth, throat or tongue swelling with breathing or swallowing difficulty, colour change, confusion, collapse or a limp, unresponsive child.',
    notes: 'Does not infer the trigger or diagnose anaphylaxis.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: WHO_IMCI_SAFETY_SOURCE_ID,
    organization: 'World Health Organization',
    title: 'Model IMCI handbook: Integrated Management of Childhood Illness',
    sourceType: 'clinical_guideline',
    reference: 'WHO reference 9241546441',
    url: 'https://www.who.int/publications/i/item/9241546441',
    publicationDate: '2005-12-06',
    accessedAt: '2026-09-21',
    locator: 'General danger signs for a sick child age 2 months up to 5 years',
    scope: 'Supports immediate action for inability to drink or breastfeed, vomiting everything, convulsions, or lethargy or unconsciousness in the covered under-five population.',
    notes: 'The product retains age in completed years; local IMNCI adaptation and clinician review remain required.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: NICE_FEVER_CHILD_SAFETY_SOURCE_ID,
    organization: 'National Institute for Health and Care Excellence',
    title: 'Fever in under 5s: assessment and initial management',
    sourceType: 'clinical_guideline',
    reference: 'NICE guideline NG143',
    url: 'https://www.nice.org.uk/guidance/ng143/chapter/Recommendations',
    accessedAt: '2026-09-21',
    locator: 'Recommendations 1.2.1 to 1.2.6 and 1.4.2',
    scope: 'Supports immediate referral for airway, breathing, circulation or consciousness compromise and recognizes failure to wake or respond normally as high risk.',
    notes: 'Applied only as a warning-sign relationship; it does not support kiosk diagnosis.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: NICE_MENINGITIS_SAFETY_SOURCE_ID,
    organization: 'National Institute for Health and Care Excellence',
    title: 'Meningitis (bacterial) and meningococcal disease: recognition, diagnosis and management',
    sourceType: 'clinical_guideline',
    reference: 'NICE guideline NG240',
    url: 'https://www.nice.org.uk/guidance/ng240/chapter/recommendations',
    publicationDate: '2024-03-19',
    accessedAt: '2026-09-21',
    locator: 'Recognition: red flag combination',
    scope: 'Supports escalation for the combined warning pattern of fever, headache, neck stiffness and altered consciousness or cognition.',
    notes: 'The rule requires the combined patient-reported pattern and does not diagnose meningitis.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: NHS_CHILD_EMERGENCY_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'What to do if your child has an accident',
    sourceType: 'government_guidance',
    reference: 'NHS child first-aid and emergency guidance',
    url: 'https://www.nhs.uk/baby/first-aid-and-safety/first-aid/what-to-do-if-your-child-has-an-accident/',
    accessedAt: '2026-09-21',
    locator: 'Call 999 if your child',
    scope: 'Supports immediate action when a child is unconscious, cannot be woken, has a seizure, or is struggling to breathe.',
    notes: 'Supports observable child warning signs across the pediatric mode; it does not diagnose a cause or validate this kiosk.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-21',
  },
  {
    id: INDIA_ERSS_SOURCE_ID,
    organization: 'Emergency Response Support System, Ministry of Home Affairs, Government of India',
    title: 'Emergency Response Support System in India',
    sourceType: 'government_guidance',
    reference: 'Government of India ERSS',
    url: 'https://112.gov.in/',
    accessedAt: ACCESSED_AT,
    locator: 'About ERSS; emergency assistance methods',
    scope: 'Supports 112 as the Pan-India single emergency number for health and other emergency assistance.',
    notes: 'Supports contact configuration only. It does not support any clinical trigger or imply that assistance has been dispatched.',
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-10',
  },
  {
    id: NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID,
    organization: 'National Health Mission, Ministry of Health and Family Welfare, Government of India',
    title: 'IMNCI Module 5: Assess and Classify the Sick Child Age 2 Months up to 5 Years',
    sourceType: 'government_guidance',
    reference: 'NHM IMNCI resource materials, Module 5',
    url: 'https://nhm.gov.in/New-Update-2022-24/CH-Programmes/Pediatric_Care/IMNCI-Resource-Materails/module_5.pdf',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: '2.0 Check for general danger signs; 3.2 Classify cough or difficult breathing; 6.2 Classify ear problem',
    scope:
      'States that ALL sick children are checked for general danger signs (not able to drink or breastfeed, vomits everything, convulsions, lethargic or unconscious) before the main symptoms, and that most children with a danger sign need urgent referral. Classifies chest indrawing or stridor in a calm child as severe disease needing urgent referral, fast breathing without those signs as a treat-today classification, and tender swelling behind the ear as mastoiditis needing urgent referral.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHM_IMNCI_YOUNG_INFANT_SAFETY_SOURCE_ID,
    organization: 'Ministry of Health and Family Welfare, Government of India, with WHO and UNICEF',
    title: 'Facility Based Integrated Management of Neonatal and Childhood Illness (F-IMNCI) Chart Booklet',
    sourceType: 'government_guidance',
    reference: 'MoHFW F-IMNCI chart booklet',
    url: 'https://nhm.gov.in/images/pdf/programmes/child-health/guidelines/facility_based_care_chartbooklet.pdf',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Assess and classify the sick young infant: possible serious bacterial infection',
    scope:
      'Lists feeling hot or cold to touch, lethargy, less than normal movements and not feeding well among the young-infant signs classified as possible serious bacterial infection needing urgent referral.',
    notes: `${PENDING_REVIEW_NOTE} The kiosk stores age in completed years, so the sign is asked for every child under one rather than only under two months.`,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_SORE_THROAT_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Sore throat',
    sourceType: 'government_guidance',
    reference: 'NHS sore throat guidance',
    url: 'https://www.nhs.uk/conditions/sore-throat/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Call 999 or go to A&E; Ask for an urgent GP appointment or get help from 111',
    scope:
      'For adults and children: difficulty breathing, being unable to swallow, drooling or a high-pitched sound when breathing in (stridor) need emergency care; a very high temperature, feeling hot, cold or shivery, or signs of dehydration need urgent advice.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_TONSILLITIS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Tonsillitis',
    sourceType: 'government_guidance',
    reference: 'NHS tonsillitis guidance',
    url: 'https://www.nhs.uk/conditions/tonsillitis/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Get help from 111; Call 999 or go to A&E',
    scope: 'A sore throat so painful that it is difficult to eat or drink needs urgent advice.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Headaches in children',
    sourceType: 'government_guidance',
    reference: 'NHS headaches in children guidance',
    url: 'https://www.nhs.uk/conditions/headaches-in-children/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Call 999 or go to A&E; Ask for an urgent GP appointment or get help from 111',
    scope:
      'A child with a headache that started suddenly and is extremely painful, a head injury in the last 3 months, a very high temperature with a stiff neck or bright lights hurting, or a rash that does not fade under a glass needs emergency care. A headache that is getting worse or wakes them at night, comes with vomiting or vision problems, or is brought on by coughing, bending or exercise needs urgent advice.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_CHILD_RASH_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Rashes in babies and children',
    sourceType: 'government_guidance',
    reference: 'NHS rashes in babies and children guidance',
    url: 'https://www.nhs.uk/conditions/rashes-babies-and-children/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Call 999 or go to A&E',
    scope: 'A rash with a stiff neck, bright lights hurting, or a rash that does not fade when a glass is pressed on it needs emergency care.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_SPRAINS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Sprains and strains',
    sourceType: 'government_guidance',
    reference: 'NHS sprains and strains guidance',
    url: 'https://www.nhs.uk/conditions/sprains-and-strains/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Go to an urgent treatment centre or call 111; Go to A&E',
    scope:
      'An injured area that has changed shape, points at an odd angle, is numb or tingling, or is discoloured or cold needs A&E; increasing swelling or bruising, or an injury that is very stiff, needs urgent advice.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_DIARRHOEA_VOMITING_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Diarrhoea and vomiting',
    sourceType: 'government_guidance',
    reference: 'NHS diarrhoea and vomiting guidance',
    url: 'https://www.nhs.uk/conditions/diarrhoea-and-vomiting/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Call 999 or go to A&E; Get help from 111',
    scope:
      'Green or yellow-green vomit in children, vomiting blood and a sudden severe tummy ache need emergency care; fewer wet nappies or peeing less, being unable to keep fluids down, or bloody diarrhoea need urgent advice.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_UTI_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Urinary tract infections (UTIs)',
    sourceType: 'government_guidance',
    reference: 'NHS urinary tract infection guidance',
    url: 'https://www.nhs.uk/conditions/urinary-tract-infections-utis/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Symptoms in adults; Symptoms in children; Ask for an urgent GP appointment or get help from NHS 111',
    scope:
      'A child aged 15 or younger with urinary symptoms needs an urgent appointment, and a high temperature or appearing generally unwell are named symptoms in children. For adults with UTI symptoms, a very high or low temperature, feeling hot or cold or shivering, and pain in the lower tummy or in the back just under the ribs are named reasons for an urgent GP appointment or NHS 111 (re-checked 2026-09-24).',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_EAR_INFECTION_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Ear infections',
    sourceType: 'government_guidance',
    reference: 'NHS ear infections guidance',
    url: 'https://www.nhs.uk/conditions/ear-infections/',
    accessedAt: PEDIATRIC_PASS_ACCESSED_AT,
    locator: 'Ask for an urgent GP appointment or get help from 111',
    scope: 'Swelling around the ear with ear infection symptoms needs urgent advice.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'accessed-2026-09-23',
  },
  {
    id: NHS_RECTAL_BLEEDING_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Bleeding from the bottom (rectal bleeding)',
    sourceType: 'government_guidance',
    reference: 'NHS rectal bleeding guidance',
    url: 'https://www.nhs.uk/conditions/bleeding-from-the-bottom-rectal-bleeding/',
    sourceUpdatedAt: '2023-04-12',
    accessedAt: NORMALIZATION_PASS_ACCESSED_AT,
    locator: 'Immediate action required: go to A&E or call 999; Urgent advice: ask for an urgent GP appointment or get help from NHS 111',
    scope:
      'Three separate levels of action. Emergency: bleeding non-stop, or a lot of blood such as the toilet water turning red or large blood clots. Urgent: poo that is black or dark red, or bloody diarrhoea. Routine GP: blood in the poo for 3 weeks. Blood that is not in the first two groups is not an emergency.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2023-04-12',
  },
  {
    id: NHS_SINUSITIS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Sinusitis (sinus infection)',
    sourceType: 'government_guidance',
    reference: 'NHS sinusitis guidance',
    url: 'https://www.nhs.uk/conditions/sinusitis-sinus-infection/',
    sourceUpdatedAt: '2024-01-31',
    accessedAt: NORMALIZATION_PASS_ACCESSED_AT,
    locator: 'Urgent advice: ask for an urgent GP appointment or get help from NHS 111',
    scope:
      'With sinusitis symptoms, feeling very unwell, painkillers not helping or symptoms getting worse need an urgent appointment. The page names no emergency (999) criteria.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2024-01-31',
  },
  {
    id: NHS_SHINGLES_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Shingles',
    sourceType: 'government_guidance',
    reference: 'NHS shingles guidance',
    url: 'https://www.nhs.uk/conditions/shingles/',
    sourceUpdatedAt: '2023-11-23',
    accessedAt: NORMALIZATION_PASS_ACCESSED_AT,
    locator: 'Urgent advice: ask for an urgent GP appointment or get help from NHS 111',
    scope:
      'With symptoms of shingles, a rash on the eye or nose, or changes to vision, need an urgent appointment. The page names no emergency (999) criteria.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2023-11-23',
  },
  {
    id: NHS_PALPITATIONS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Heart palpitations',
    sourceType: 'government_guidance',
    reference: 'NHS heart palpitations guidance',
    url: 'https://www.nhs.uk/conditions/heart-palpitations/',
    sourceUpdatedAt: '2026-03-17',
    accessedAt: RECONCILIATION_PASS_ACCESSED_AT,
    locator: 'Immediate action required: call 999 or go to A&E',
    scope:
      'Call 999 or go to A&E if you have heart palpitations now and they do not go away, or with chest pain, shortness of breath, or feeling faint or fainting.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2026-03-17',
  },
  {
    id: NICE_NEUROLOGICAL_REFERRAL_SAFETY_SOURCE_ID,
    organization: 'National Institute for Health and Care Excellence',
    title: 'Suspected neurological conditions: recognition and referral (NG127)',
    sourceType: 'clinical_guideline',
    reference: 'NICE NG127 recommendations 1.7.2, 1.7.3, 1.7.5 and 1.10.2',
    url: 'https://www.nice.org.uk/guidance/ng127/chapter/Recommendations',
    sourceUpdatedAt: '2019-05-01',
    accessedAt: RECONCILIATION_PASS_ACCESSED_AT,
    locator: 'Recommendations 1.7.2, 1.7.3, 1.7.5 and 1.10.2',
    scope:
      'Refer immediately adults with rapidly progressive symmetrical limb weakness (1.7.2) or rapidly progressive symmetrical numbness and weakness or imbalance (1.10.2); with slowly progressive weakness, refer immediately if there is breathlessness at rest or lying flat and urgently if swallowing is impaired (1.7.5); refer immediately severe low back pain radiating into the leg with new bladder, bowel or sexual disturbance or perineal numbness (1.7.3). Adults only.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'ng127-2019',
  },
  {
    id: NHS_BACK_PAIN_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Back pain',
    sourceType: 'government_guidance',
    reference: 'NHS back pain guidance',
    url: 'https://www.nhs.uk/conditions/back-pain/',
    sourceUpdatedAt: '2026-03-05',
    accessedAt: RECONCILIATION_PASS_ACCESSED_AT,
    locator: 'Immediate action required: call 999 or go to A&E',
    scope:
      'Call 999 for back pain with pain, tingling, weakness or numbness in both legs, loss of feeling around the genitals or anus, or new difficulty peeing or controlling the bladder or bowels.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2026-03-05',
  },
  {
    id: NHS_SCIATICA_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Sciatica',
    sourceType: 'government_guidance',
    reference: 'NHS sciatica guidance',
    url: 'https://www.nhs.uk/conditions/sciatica/',
    sourceUpdatedAt: '2024-12-03',
    accessedAt: RECONCILIATION_PASS_ACCESSED_AT,
    locator: 'Immediate action required: call 999 or go to A&E',
    scope:
      'Call 999 for sciatica on both sides, severe or worsening weakness or numbness in both legs, numbness around the genitals or anus, or loss of bladder or bowel control.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2024-12-03',
  },
  {
    id: NHS_BROKEN_RIBS_SAFETY_SOURCE_ID,
    organization: 'National Health Service',
    title: 'Broken or bruised ribs',
    sourceType: 'government_guidance',
    reference: 'NHS broken or bruised ribs guidance',
    url: 'https://www.nhs.uk/conditions/broken-or-bruised-ribs/',
    sourceUpdatedAt: '2024-01-10',
    accessedAt: BLOCKER_PASS_ACCESSED_AT,
    locator: 'Immediate action required: call 999 or go to A&E',
    scope:
      'Call 999 if the injury was caused by a serious accident such as a car accident, shortness of breath or chest pain is getting worse, there is pain in the tummy or shoulder, or blood is coughed up: a broken rib may have damaged the lung, liver or spleen.',
    notes: PENDING_REVIEW_NOTE,
    reviewStatus: 'reviewed',
    evidenceStatus: 'qualitative_supported',
    version: 'reviewed-2024-01-10',
  },
];

const SYSTEM_LIMITATION =
  'Supports the warning-sign relationship and stated level of action only. It does not clinically validate DocMatch+, replace clinical judgment, or prove system-level safety.';

export const R3_SAFETY_EVIDENCE_REGISTER: readonly SafetyEvidenceRegisterEntry[] = [
  {
    sourceId: AHA_CHEST_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['upper-abdominal-exertional-associated-warning'],
    supports: 'Upper-abdominal discomfort can be an anginal equivalent, and exertion, sweating, and breathlessness are relevant assessment features.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: AHA_WARNING_SIGNS_SOURCE_ID,
    ruleIds: ['upper-abdominal-exertional-associated-warning'],
    supports: 'Stomach discomfort with shortness of breath or cold sweat belongs among warning signs for which emergency help should not be delayed.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_BREATHLESSNESS_SAFETY_SOURCE_ID,
    ruleIds: [
      'breathing-severe-inability-to-speak',
      'breathing-pale-blue-grey-skin',
      'breathing-sudden-confusion',
      'breathing-coughing-blood',
    ],
    supports: 'The named breathing features map to explicit immediate or urgent action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_HEADACHE_SAFETY_SOURCE_ID,
    ruleIds: [
      'headache-sudden-extremely-painful',
      'headache-new-one-sided-weakness',
      'headache-speech-memory-vision-change',
      'headache-drowsy-confused',
    ],
    supports: 'The named acute headache features map to explicit immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NICE_HEADACHE_SAFETY_SOURCE_ID,
    ruleIds: [
      'headache-sudden-extremely-painful',
      'headache-new-one-sided-weakness',
      'headache-speech-memory-vision-change',
      'headache-drowsy-confused',
    ],
    supports: 'The same concepts warrant further evaluation or referral in NICE guidance.',
    doesNotSupport: 'Does not alone support the emergency action payload; that action is grounded in the NHS immediate-action source.',
  },
  {
    sourceId: NHS_JOINT_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['joint-injury-severe-or-displaced', 'joint-injury-sensation-or-circulation-change', 'joint-sudden-hot-swollen'],
    supports: 'The named injury signs map to immediate action, while a hot swollen joint maps to urgent assessment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_ARTHRITIS_SAFETY_SOURCE_ID,
    ruleIds: ['joint-sudden-hot-swollen'],
    supports: 'Sudden severe single-joint pain and swelling or red/hot skin warrants urgent assessment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_PELVIC_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['lower-abdominal-severe-or-faint', 'lower-abdominal-heavy-bleeding'],
    supports: 'The named severe pain, movement or touch sensitivity, faintness and heavy bleeding features map to immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_EYE_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['eye-sudden-vision-loss-or-injury'],
    supports: 'Sudden loss of vision, a pierced eye or an object stuck in the eye maps to immediate assessment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_NOSEBLEED_SAFETY_SOURCE_ID,
    ruleIds: ['nosebleed-prolonged-or-excessive'],
    supports: 'The named prolonged, excessive, injury-associated or systemic bleeding features map to immediate-assessment guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_STROKE_SAFETY_SOURCE_ID,
    ruleIds: ['generic-new-neurological-change', 'pediatric-sudden-neurological-change'],
    supports: 'Sudden facial or one-sided weakness, speech difficulty, numbness and sudden visual loss map to immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_CHEST_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['chest-persistent-spreading-associated'],
    supports: 'Persistent sudden chest discomfort with spread or the named associated symptoms maps to immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_ALLERGY_SAFETY_SOURCE_ID,
    ruleIds: ['generic-severe-breathing', 'skin-airway-swelling'],
    supports: 'Severe breathing difficulty and sudden mouth or throat swelling with breathing or swallowing difficulty map to immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: WHO_IMCI_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-seizure-or-unresponsive', 'pediatric-unable-to-drink-or-vomits-everything'],
    supports: 'Not able to drink or breastfeed, vomiting everything, convulsions, and lethargy or unconsciousness are IMCI general danger signs, each needing urgent referral.',
    doesNotSupport: 'Does not cover all ages under 18, does not replace national IMNCI adaptation, and does not validate this kiosk.',
  },
  {
    sourceId: NICE_FEVER_CHILD_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-struggling-to-breathe', 'pediatric-seizure-or-unresponsive'],
    supports: 'Airway, breathing, circulation or consciousness compromise and failure to wake or respond normally require immediate referral.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NICE_MENINGITIS_SAFETY_SOURCE_ID,
    ruleIds: ['neck-meningitis-warning-pattern'],
    supports: 'The combined fever, headache, neck stiffness and altered-awareness pattern is a source-defined red-flag combination.',
    doesNotSupport: 'Does not diagnose meningitis and does not support escalation from neck location alone.',
  },
  {
    sourceId: NHS_HEADACHE_SAFETY_SOURCE_ID,
    ruleIds: ['generic-unresponsive-or-seizure'],
    supports: 'Seizure and reduced consciousness map to explicit immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_BREATHLESSNESS_SAFETY_SOURCE_ID,
    ruleIds: ['generic-severe-breathing', 'pediatric-struggling-to-breathe'],
    supports: 'Gasping, choking or inability to speak because of breathing difficulty maps to immediate-action guidance.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_CHILD_EMERGENCY_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-struggling-to-breathe', 'pediatric-seizure-or-unresponsive'],
    supports: 'A child who is unconscious, cannot be woken, has a seizure, or is struggling to breathe needs immediate emergency assessment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHM_IMNCI_SICK_CHILD_SAFETY_SOURCE_ID,
    ruleIds: [
      'pediatric-seizure-or-unresponsive',
      'pediatric-unable-to-drink-or-vomits-everything',
      'pediatric-chest-indrawing-or-stridor',
      'pediatric-fast-breathing',
      'throat-airway-danger',
      'pediatric-under-five-swelling-behind-ear',
    ],
    supports:
      'Government of India IMNCI: every sick child is checked for general danger signs first; chest indrawing, stridor in a calm child and tender swelling behind the ear need urgent referral; fast breathing alone is a treat-today classification.',
    doesNotSupport: 'Covers children 2 months up to 5 years. Does not diagnose pneumonia or mastoiditis and does not validate this kiosk.',
  },
  {
    sourceId: NHM_IMNCI_YOUNG_INFANT_SAFETY_SOURCE_ID,
    ruleIds: ['infant-serious-illness-sign'],
    supports: 'Not feeding well, reduced movement, lethargy and feeling hot or cold in a young infant are signs classified for urgent referral.',
    doesNotSupport:
      'Does not cover every child under one: it is defined for young infants, and the kiosk applies it to every child under one because age is held in completed years. Does not validate this kiosk.',
  },
  {
    sourceId: NHS_SORE_THROAT_SAFETY_SOURCE_ID,
    ruleIds: ['throat-airway-danger', 'throat-urgent-review'],
    supports: 'Breathing or swallowing difficulty, drooling and stridor need emergency care; a very high temperature, shivering or dehydration need urgent advice.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_TONSILLITIS_SAFETY_SOURCE_ID,
    ruleIds: ['throat-urgent-review'],
    supports: 'A sore throat so painful that eating or drinking is difficult needs urgent advice.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_CHILD_HEADACHE_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-headache-sudden-or-recent-injury', 'pediatric-fever-stiff-neck-or-rash', 'pediatric-headache-urgent-features'],
    supports: 'The named child headache features map to emergency or urgent action as stated.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_CHILD_RASH_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-fever-stiff-neck-or-rash'],
    supports: 'A rash that does not fade under a glass, or a rash with a stiff neck or light sensitivity, needs emergency care.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_SPRAINS_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-injury-emergency', 'injury-worsening-urgent'],
    supports: 'A changed shape, odd angle, numbness or coldness after injury needs A&E; worsening swelling or bruising or marked stiffness needs urgent advice.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_JOINT_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-injury-emergency'],
    supports: 'Very bad pain after an injury, being unable to put weight on a joint, or a joint out of place needs A&E.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_DIARRHOEA_VOMITING_SAFETY_SOURCE_ID,
    ruleIds: ['pediatric-abdominal-emergency', 'pediatric-dehydration-urgent'],
    supports: 'Green vomit in a child, vomiting blood and sudden severe tummy pain need emergency care; reduced urine, fluids not staying down or bloody diarrhoea need urgent advice.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_UTI_SAFETY_SOURCE_ID,
    ruleIds: ['urinary-unwell-urgent'],
    supports: 'A child with urinary symptoms needs an urgent appointment; fever and appearing unwell are named symptoms in children. An adult with urinary symptoms and a high or low temperature, shivering, or pain in the back just under the ribs needs an urgent appointment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_EAR_INFECTION_SAFETY_SOURCE_ID,
    ruleIds: ['ear-swelling-around-ear-urgent'],
    supports: 'Swelling around the ear with ear symptoms needs urgent advice.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_RECTAL_BLEEDING_SAFETY_SOURCE_ID,
    ruleIds: ['rectal-bleeding-heavy', 'rectal-bleeding-urgent'],
    supports: 'Non-stop bleeding or a lot of blood from the bottom needs emergency care; black or dark red poo, or bloody diarrhoea, needs an urgent appointment. Other reported blood is a routine GP matter and is not escalated.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_SINUSITIS_SAFETY_SOURCE_ID,
    ruleIds: ['sinus-urgent-review'],
    supports: 'Feeling very unwell, painkillers not helping or symptoms getting worse with sinus symptoms needs an urgent appointment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_SHINGLES_SAFETY_SOURCE_ID,
    ruleIds: ['face-rash-eye-nose-urgent'],
    supports: 'A facial rash on the eye or nose, or a change in vision, with shingles-type symptoms needs an urgent appointment.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_PALPITATIONS_SAFETY_SOURCE_ID,
    ruleIds: ['palpitations-emergency-features'],
    supports: 'Palpitations that do not go away, or come with chest pain, shortness of breath or feeling faint or fainting, need 999 or A&E.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NICE_NEUROLOGICAL_REFERRAL_SAFETY_SOURCE_ID,
    ruleIds: ['neuro-rapidly-progressive-weakness', 'back-cauda-equina-pattern'],
    supports: 'Rapidly progressive symmetrical weakness or numbness, weakness with breathing or swallowing difficulty, and back pain into the leg with new bladder, bowel or perineal change are referred immediately.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_BACK_PAIN_SAFETY_SOURCE_ID,
    ruleIds: ['back-cauda-equina-pattern'],
    supports: 'Back pain with symptoms in both legs, numbness around the genitals or anus, or new bladder or bowel change needs 999 or A&E.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_SCIATICA_SAFETY_SOURCE_ID,
    ruleIds: ['back-cauda-equina-pattern'],
    supports: 'Sciatica on both sides, weakness or numbness in both legs, numbness around the genitals or anus, or loss of bladder or bowel control needs 999 or A&E.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: NHS_BROKEN_RIBS_SAFETY_SOURCE_ID,
    ruleIds: ['upper-abdomen-injury-emergency'],
    supports: 'After an injury to the ribs or upper body, a serious accident, worsening breathlessness or chest pain, shoulder pain or coughing up blood needs 999 or A&E.',
    doesNotSupport: SYSTEM_LIMITATION,
  },
  {
    sourceId: INDIA_ERSS_SOURCE_ID,
    ruleIds: [],
    supports: '112 is the Pan-India emergency number used by the emergency payload.',
    doesNotSupport: 'Does not support clinical predicates and does not prove that a call or dispatch occurred.',
  },
];
