/** Editorial reference taxonomy only. Never use this array for clinical routing. */
export const specialtyLandscape = [
  'Family Medicine',
  'Internal Medicine',
  'Pediatrics',
  'OB/GYN',
  'Geriatric Medicine',
  'Cardiology',
  'Interventional Cardiology',
  'Electrophysiology',
  'Advanced Heart Failure & Transplant Cardiology',
  'Gastroenterology',
  'Hepatology',
  'Transplant Hepatology',
  'Pulmonology',
  'Pulmonary Critical Care',
  'Hematology',
  'Oncology',
  'Cancer Immunology',
  'Rheumatology',
  'Endocrinology',
  'Reproductive Endocrinology',
  'Nephrology',
  'Infectious Diseases',
  'Allergy & Immunology',
  'Medical Genetics & Genomics',
  'Clinical Informatics',
  'Medical Toxicology',
  'Sleep Medicine',
  'Obesity Medicine',
  'Transplant Medicine',
  'Occupational Medicine',
  'Headache Medicine',
  'Pain Medicine',
  'Palliative Care',
  'Hospice Medicine',
  'General Surgery',
  'Trauma Surgery',
  'Colorectal Surgery',
  'Bariatric Surgery',
  'Burn Surgery',
  'Surgical Oncology',
  'Hepato-Pancreato-Biliary (HPB) Surgery',
  'Transplant Surgery',
  'Vascular Surgery',
  'Cardiothoracic Surgery',
  'Thoracic Surgery',
  'Neurosurgery',
  'Endovascular Neurosurgery',
  'Pediatric Neurosurgery',
  'Orthopedic Surgery',
  'Spine Surgery',
  'Hand Surgery',
  'Foot and Ankle Surgery',
  'Plastic Surgery',
  'Aesthetic Surgery',
  'Craniofacial Surgery',
  'Microsurgery',
  'Breast Reconstruction',
  'Gender Surgery',
  'Otolaryngology (ENT)',
  'Head and Neck Surgery',
  'Laryngology',
  'Facial Plastic Surgery',
  'Oral and Maxillofacial Surgery',
  'Urology',
  'Female Urology',
  'Pediatric Urology',
  'Gynecologic Oncology',
  'Maternal-Fetal Medicine',
  'Urogynecology',
  'Pediatric Surgery',
  'Fetal Surgery',
  'Neurology',
  'Vascular Neurology',
  'Epileptology',
  'Neuromuscular Medicine',
  'Neuro-oncology',
  'Behavioral Neurology',
  'Dermatology',
  'Ophthalmology',
  'Physical Medicine & Rehabilitation',
  'Sports Medicine',
  'Radiation Oncology',
  'Forensic Pathology',
  'Preventive Medicine',
  'Lifestyle Medicine',
  'Wilderness Medicine',
  'Anesthesiology',
  'Pediatric Anesthesiology',
  'Cardiac Anesthesiology',
  'Obstetric Anesthesiology',
  'Neuroanesthesiology',
  'Regional Anesthesia & Acute Pain',
  'Emergency Medicine',
  'Pediatric Emergency Medicine',
  'Critical Care Medicine',
  'Diagnostic Radiology',
  'Interventional Radiology',
  'Nuclear Radiology',
  'Neuroradiology',
  'Musculoskeletal Radiology',
  'Breast Imaging Radiology',
  'Pathology',
  'Genetic Pathology',
  'Molecular Pathology',
  'Neuropathology',
  'Transfusion Medicine',
  'Psychiatry',
  'Child & Adolescent Psychiatry',
  'Geriatric Psychiatry',
  'Forensic Psychiatry',
  'Addiction Psychiatry',
  'Consultation-Liaison Psychiatry',
  'Military Psychiatry',
  'Neonatology',
  'Pediatric Intensivist',
  'Pediatric Cardiology',
  'Pediatric Neurology',
  'Pediatric Endocrinology',
  'Pediatric Gastroenterology',
  'Pediatric Hematology & Oncology',
  'Pediatric Infectious Disease',
  'Pediatric Rheumatology',
  'Pediatric Pulmonology',
  'Pediatric Nephrology',
  'Pediatric Dermatology',
  'Pediatric Ophthalmology',
  'Pediatric Orthopedics',
  'Pediatric Plastic Surgery',
  'Developmental-Behavioral Pediatrics',
  'Hyperbaric Medicine',
  'Aerospace Medicine',
  'Undersea Medicine',
  'Longevity Medicine',
  'Integrative Medicine',
  'Culinary Medicine',
  'Global Health',
  'Military Medicine',
  'Medical Science & Research',
  'Concierge & Direct Primary Care',
  'Telemedicine',
  'Correctional Medicine',
  'Public Health Medicine',
] as const;
